### PR TITLE
Fix LMDB commit transaction when execution freezes

### LINKED ISSUE #2963: LMDB store sometimes block in execution
Bug is reproducible with this test when number of validators are more than 19 (?).
https://github.com/rchain/rchain/blob/8fb7bc466ea/casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala#L391

Problem is showing is LMDB _commit_ is called with suspended execution (Sync.delay).
https://github.com/rchain/rchain/blob/98cbac41a0202840011d2d4977260029250fea78/casper/src/main/scala/coop/rchain/casper/storage/LmdbKeyValueStore.scala#L32-L37

### PR DESCRIPTION
**Pull request by tgrospic**
## Overview
LMDB has limitation for write transactions to be used on a single thread. 
https://lmdb.readthedocs.io/en/release/#threads

This PR fixes the implementation of LMDB store to not use suspended execution (Sync.delay) which can cause changing threads. This applies to read and write transactions because freezing of execution was noticed in both cases.

For the reference this was the buggy code.
https://github.com/rchain/rchain/blob/899954e422/casper/src/main/scala/coop/rchain/casper/storage/LmdbKeyValueStore.scala#L21-L50

---

In this PR is also fix for CI to pass tests. Memory limit is set separately for integration tests with lower value and with more memory for unit tests.

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by zsluedem — APPROVED** [review]
Very good found out~! I am thinking is this the cause of the tuple space mismatch also.

**Comment by tgrospic** [comment]
@zsluedem this code is not used in RSpace currently. But we should investigate if similar scenario is involved with existing implementation when processing operations in parallel.
https://github.com/rchain/rchain/blob/2560ab8de280c727560d7819f23fed9dd4286a8f/rspace/src/main/scala/coop/rchain/rspace/history/HistoryInstances.scala#L318-L321

File: casper/src/main/scala/coop/rchain/casper/storage/LmdbKeyValueStore.scala [hunk 1]
```diff
@@ -10,78 +10,108 @@ import coop.rchain.shared.Resources.withResource
...
+//                   Sync[F].delay(txn.close()) *> done
+//                 case (txn, Error(_)) =>
+//                   // Close transaction on error.
+//                   Sync[F].delay(txn.close()) *> done
+//                 case (_, Canceled) =>
+//                   // When execution is canceled, closing transaction throws NotReadyException
+//                   //  in bracket `use` function which is not visible in bracket `release` (?).
+//                   done
+//               }
+//    } yield result
```
Comment (tgrospic) [inline casper/src/main/scala/coop/rchain/casper/storage/LmdbKeyValueStore.scala]: TEMP

**Review by nzpr — APPROVED** [review]
I cannot reproduce freeze anymore, so this helped!

**Comment by tgrospic** [comment]
I moved change with memory limit on CI to this PR to be able to pass tests.

**Comment by tgrospic** [comment]
bors merge
