### PR TITLE
use PROXY_SAFE for lmdb 

### LINKED ISSUE #3116: debug infor for history store
## Overview
The node would encounter bug like below.
```
java.lang.Exception: 0: cannot acquire 256 bits from a vector that contains 252 bits at coop.rchain.shared.AttemptOpsF$.ex(AttemptOpsF.scala:10) at coop.rchain.shared.AttemptOpsF$RichAttempt.get(AttemptOpsF.scala:19) at coop.rchain.rspace.history.HistoryStoreInstances$$anon$1.$anonfun$get$2(HistoryStore.scala:38) at cats.instances.OptionInstances$$anon$1.traverse(option.scala:87) at cats.instances.OptionInstances$$anon$1.traverse(option.scala:15) at cats.Traverse$Ops.traverse(Traverse.scala:19) at cats.Traverse$Ops.traverse$(Traverse.scala:19) at cats.Traverse$ToTraverseOps$$anon$2.traverse(Traverse.scala:19) at coop.rchain.rspace.history.HistoryStoreInstances$$anon$1.$anonfun$get$1(HistoryStore.scala:38) at scala.Function1.$anonfun$andThen$1(Function1.scala:57) at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:170) at monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$1(TaskRunLoop.scala:222) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) at java.base/java.util.concurrent.FutureTask.run(Unknown Source) at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source)
```

We don't know the condition to reproduce the situation. Current solution is to put more debug info into the history store when this bug happened.

### LINKED ISSUE #3127: What is the performance lost in lmdb proxy_safe compared to proxy_optimal?
Related documents:
https://github.com/lmdbjava/lmdbjava/wiki/Buffers#bytebuffer

java lmdb provided two different buffer proxy for `DirectBuffer` in jvm.

Currently rnode using `PROXY_OPTIMAL` which is not safe in jvm(jvm doesn't encourage the opertion does by `PROXY_OPTIMAL`). THere is another option for bufferproxy which is `PROXY_SAFE`.

What is the performance differences between these two bufferproxy?

### PR DESCRIPTION
**Pull request by zsluedem**
## Overview
~~put debug info in history store when error happen~~

Use PROXY_SAFE for lmdb

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

File: rspace/src/main/scala/coop/rchain/rspace/history/HistoryStore.scala [hunk 1]
```diff
@@ -35,7 +37,24 @@ object HistoryStoreInstances {
     override def get(key: Blake2b256Hash): F[Trie] =
       for {
         maybeBytes <- store.get(key)
```
Comment (nzpr) [inline rspace/src/main/scala/coop/rchain/rspace/history/HistoryStore.scala]: I know this is aesthetic but I have an allergy to these `maybe` names. 
Can we use `bytesOpt`?
Actually we should have everywhere `unsafeGet` extensions, so we don't have tons of such options across code that expresses useful logic.

**Review by nzpr — APPROVED** [review]
LGTM

File: rspace/src/main/scala/coop/rchain/rspace/history/HistoryStore.scala (hunk 1 above)
Comment (tgrospic) [reply rspace/src/main/scala/coop/rchain/rspace/history/HistoryStore.scala]: In Haskell `Maybe` type represents the same type as `Option` in Scala so from that perspective both of these terms makes sense. But I agree if we want to be more precise in naming.

I agree that `unsafe` extensions can simplify the code but only in situations where the value is expected and generic error is thrown otherwise. So here it is more applicable to `Trie.codecTrie.unsafeDecode(bytes)` instead to store get. (which is similar what `Trie.codecTrie.decode(bytes).get` is doing)

File: rspace/src/main/scala/coop/rchain/rspace/history/HistoryStore.scala [hunk 2]
```diff
@@ -34,8 +36,25 @@ object HistoryStoreInstances {
...
+                                  Sync[F].pure(res)
+                                case Attempt.Failure(err) =>
+                                  Sync[F]
+                                    .raiseError[DecodeResult[Trie]](
+                                      new Exception(
+                                        s"Key: ${Base16.encode(key.bytes.toArray)}\nValue: ${Base16
+                                          .encode(bytes.toByteArray)}\n${err.toString()}"
+                                      )
+                                    )
+                              }
```
Comment (tgrospic) [inline rspace/src/main/scala/coop/rchain/rspace/history/HistoryStore.scala]: The work of converting `Attempt` to Applicative error is already done in `decode(..).get` so here we can just "hook" on the error to display additional info. `onError` does not handle the error.
```scala
result <- maybeBytes.traverse { bytes =>
            Trie.codecTrie.decode(bytes).get.onError {
              case ex: Throwable =>
                val errMsg =
                  s"Key: ${Base16.encode(key.bytes.toArray)}\nValue: ${bytes.toHex}"
                Log[F].error(errMsg, ex)
            }
          }
```
Can you also try to implement retry logic so we can see if very next get will have the same error?

File: rspace/src/main/scala/coop/rchain/rspace/history/Store.scala [hunk 3]
```diff
@@ -34,7 +35,7 @@ object StoreInstances {
     for {
       env <- Sync[F].delay {
               Env
-                .create()
+                .create(PROXY_SAFE)
```
Comment (tgrospic) [inline rspace/src/main/scala/coop/rchain/rspace/history/Store.scala:43]: Do you know what is performance impact of "safe buffers"?

**Comment by nzpr** [comment]
With merging https://github.com/rchain/rchain/pull/3121 we don't need this PR anymore, right?

**Comment by tgrospic** [comment]
> With merging #3121 we don't need this PR anymore, right?

Let's keep it a little longer. Also I'm interested if it makes sense to use `PROXY_SAFE` option for buffers.

File: rspace/src/main/scala/coop/rchain/rspace/history/Store.scala (hunk 3 above)
Comment (zsluedem) [reply rspace/src/main/scala/coop/rchain/rspace/history/Store.scala:43]: https://github.com/rchain/rchain/issues/3127

**Comment by zsluedem** [comment]
@nzpr @tgrospic Wanna use ProxySafe?

**Review by tgrospic — APPROVED** [review]
LGTM

**Comment by zsluedem** [comment]
bors merge

**Comment by zsluedem** [comment]
https://github.com/rchain/rchain/issues/3127 performance impact for using PROXY_SAFE

**Comment by zsluedem** [comment]
bors merge
