### PR TITLE
Fix history trie encoding problem

### LINKED ISSUE #3491: Fix history (Trie) and cold store value hash
## Overview

Rholang state in RNode is stored in a Merkle tree with channels as keys and channel data as values (tuple space).

Merkle tree implementation has two components: History and Cold (leaf) store. History represents the tree structure with hashes on the leaf nodes that points to values in the Cold store.

History key is calculated from the hash value of its children nodes. Cold store key is calculated from the value itself that is stored on a key.
The problem is that input used to get the hash in History and Cold store does not represent the whole value (base type codec) but the sub-type which is missing discriminator encoded data.

This made LFS sync much harder, because validation needs to deserialize each value to get to the input for hashing.

For History.

https://github.com/rchain/rchain/blob/dd95fb0f014a4c254afe9476c2e810192fcaf1a4/rspace/src/main/scala/coop/rchain/rspace/state/RSpaceImporter.scala#L68-L78

And Cold store.

https://github.com/rchain/rchain/blob/dd95fb0f014a4c254afe9476c2e810192fcaf1a4/rspace/src/main/scala/coop/rchain/rspace/state/RSpaceImporter.scala#L99-L107

## Solution

Use base type codec to serialize the value and use as input for hashing.

Remove additional work done in LFS validation.

### History (Trie)

Hash of the `Trie` type is executed lazily and stored on the object itself. Function to calculate hash is just matching on sub-type and reads this value. The bug is that sub-type is using its own specific codec instead of the base type `Trie`.

https://github.com/rchain/rchain/blob/01c4a1e6d24fe0813377dabbe8031a806e5deeb6/rspace/src/main/scala/coop/rchain/rspace/history/History.scala#L105-L115

This should be fixed by using `Trie` codec to get the serialized value for hashing, because this is the complete binary that is stored.

`PointerBlock`

https://github.com/rchain/rchain/blob/01c4a1e6d24fe0813377dabbe8031a806e5deeb6/rspace/src/main/scala/coop/rchain/rspace/history/History.scala#L88

```scala
lazy val encoded: BitVector = codecTrie.encode(this).getUnsafe
```

`Skip`

https://github.com/rchain/rchain/blob/01c4a1e6d24fe0813377dabbe8031a806e5deeb6/rspace/src/main/scala/coop/rchain/rspace/history/History.scala#L72

```scala
lazy val encoded: BitVector = codecTrie.encode(this).getUnsafe
```

Surprisingly `EmptyTrie` is using correct codec.

https://github.com/rchain/rchain/blob/01c4a1e6d24fe0813377dabbe8031a806e5deeb6/rspace/src/main/scala/coop/rchain/rspace/history/History.scala#L42

### Cold store 

Here is the example for Produce (it's similar with Consume and Joins) where the value that is used as input for hashing is not the serialized `PersistedData` as the base type but the specific inherited class.

https://github.com/rchain/rchain/blob/ad9514a903dcff0e265c0a509ab5adfae5b26b5d/rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala#L114-L120

This should be fixed by using `PersistedData` codec to get the serialized value for hashing, because this is the complete binary that is stored.

```scala
val dataLeaf    = DataLeaf(data)
val dataEncoded = codecPersistedData.encode(dataLeaf).getUnsafe.toByteVector
val dataHash    = Blake2b256Hash.create(dataEncoded)
```

### PR DESCRIPTION
**Pull request by zsluedem**
## Overview

This issue is trying to address https://github.com/rchain/rchain/issues/3491.

The issue itself explain very details on the problem. So I would skip explain here.

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

File: rspace/src/main/scala/coop/rchain/rspace/serializers/ScodecSerialize.scala [hunk 1]
```diff
@@ -216,7 +195,31 @@ object ScodecSerialize {
...
 
-  implicit def codecTrieValuePointer: Codec[ValuePointer] =
+  /**
+    * FIXME There some problem with fixed length vector for `VectorOfN(provide(2), int32)` which when you encode
+    *        Vector(1) with only one element would be successful but decode the generated byteVector would fail.
+    *        example:
+    *         val codecVector = vectorOfN(provide(2), int32)
+    *         val encoded = codecVector.encode(Vector(1))  // success
+    *         val decoded = codecVector.decode(encoded.toOption.get)  // fail
+    *        There are limitation on creating method of PointerBlock which garantees length 256.
```
Comment (zsluedem) [inline rspace/src/main/scala/coop/rchain/rspace/serializers/ScodecSerialize.scala]: Maybe I should fix this now?

File: rspace/src/main/scala/coop/rchain/rspace/serializers/ScodecSerialize.scala [hunk 2]
```diff
@@ -166,41 +166,20 @@ object ScodecSerialize {
     (codecConsume :: codecSeq(codecProduce) :: sortedSet(uint8) :: codecMap(codecProduce, int32))
       .as[COMM]
 
-  val codecSkip: Codec[Skip] = (codecByteVector :: codecTrieValuePointer).as[Skip]
-
-  val memoizingSkipCodec: Codec[Skip] =
-    Codec.apply((s: Skip) => Attempt.successful(s.encoded), codecSkip.decode)
```
Comment (zsluedem) [inline rspace/src/main/scala/coop/rchain/rspace/serializers/ScodecSerialize.scala:172]: Remove this because it cause infinite loop on calling method which full the stack

Comment (zsluedem) [reply rspace/src/main/scala/coop/rchain/rspace/serializers/ScodecSerialize.scala:172]: Skip and PointerBlock are not abstract but concrete here.

File: rspace/src/main/scala/coop/rchain/rspace/history/History.scala [hunk 3]
```diff
@@ -113,6 +113,8 @@ object Trie {
       case s: Skip           => s.hash
       case _: EmptyTrie.type => History.emptyRootHash
     }
+
+  def hash(bytes: ByteVector): Blake2b256Hash = Blake2b256Hash.create(bytes)
```
Comment (tgrospic) [inline rspace/src/main/scala/coop/rchain/rspace/history/History.scala]: This function does not relates to Trie and importer can use Blake2b256Hash directly as it already does.

TODO comment can now be removed.

File: rspace/src/main/scala/coop/rchain/rspace/state/RSpaceImporter.scala [hunk 4]
```diff
@@ -90,34 +85,30 @@ object RSpaceImporter {
...
+                  case DataLeaf(bytes)          => decodeDatums[A](bytes)
+                  case ContinuationsLeaf(bytes) => decodeContinuations[P, K](bytes)
+                }
+                .void
+                .handleErrorWith { ex: Throwable =>
+                  raiseErrorEx(
+                    s"Decode inner class of key: ${hash.bytes.toHex}.",
+                    ex
+                  )
+                }
```
Comment (tgrospic) [inline rspace/src/main/scala/coop/rchain/rspace/state/RSpaceImporter.scala]: Now, we don't need decoding part of the code anymore. When hash matches no other checks are needed.

File: rspace/src/main/scala/coop/rchain/rspace/serializers/ScodecSerialize.scala (hunk 1 above)
Comment (tgrospic) [reply rspace/src/main/scala/coop/rchain/rspace/serializers/ScodecSerialize.scala]: This is expected behavior with `provide` codec because information about length is not part of encoded data, so decoding the value which is not the same length as specified in _provide_ will fail.

Here is the example, using _provide_ will not encode length so decoder will expect the size 3.
```scala
val c1 = vectorOfN(provide(3), uint4)
c1.encode(Vector(1, 2, 3)).getUnsafe // BitVector(12 bits, 0x123)

val c2 = vectorOfN(uint4, uint4)
c2.encode(Vector(1, 2, 3)).getUnsafe // BitVector(16 bits, 0x3123)
```

Because PointerBlock is always created with fixed length (256), _provide_ codec can be used here.
https://github.com/rchain/rchain/blob/02c276ff4fe04415b0262e02fb3dd69ebda48533/rspace/src/main/scala/coop/rchain/rspace/history/History.scala#L120-L123

File: rspace/src/main/scala/coop/rchain/rspace/serializers/ScodecSerialize.scala (hunk 2 above)
Comment (tgrospic) [reply rspace/src/main/scala/coop/rchain/rspace/serializers/ScodecSerialize.scala:172]: :+1:

File: rspace/src/main/scala/coop/rchain/rspace/serializers/ScodecSerialize.scala (hunk 1 above)
Comment (zsluedem) [reply rspace/src/main/scala/coop/rchain/rspace/serializers/ScodecSerialize.scala]: This is an unsafe function from my perspective. Anyway, just want to mention that.

Comment (zsluedem) [reply rspace/src/main/scala/coop/rchain/rspace/serializers/ScodecSerialize.scala]: I would remove the comment.

**Review by tgrospic — APPROVED** [review]
LGTM
