### PR TITLE
Fix transaction API error

### LINKED ISSUE #3740: Transaction api returns error when blockhash is empty
### What did you expect to see?
404 or 502 in https://observer-exch2.services.mainnet.rchain.coop/api/transactions/

### What did you see instead?
```
2022-06-16 04:56:22,307 [ERROR] [node-runner-27      ] [Routes$ResponseErrorHandler$1]- HTTP API response error
org.lmdbjava.Dbi$BadValueSizeException: Unsupported size of key/DB name/data, or wrong DUPFIXED size (-30781)
        at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:72)
        at org.lmdbjava.Dbi.get(Dbi.java:239)
        at coop.rchain.store.LmdbKeyValueStore.$anonfun$get$2(LmdbKeyValueStore.scala:62)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
```

### PR DESCRIPTION
**Pull request by stanislavlyalin**
## Overview

The problem was due to an exception in the `Dbi.get` method when passing an empty hash. The node did not shut down, but the clients received an uninformative message, and the node administrator saw an error message in the log.

Now the message is displayed in the log as a warning. Additionally, it is checked that the hash is not empty. Node clients now see the response when making a request:
```json
"Block hash cannot be empty."
```
which has more sense.

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

File: node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala [hunk 1]
```diff
@@ -36,7 +36,12 @@ object WebApiRoutes {
             case err: BlockApiException => BadRequest(err.getMessageSafe.asJson)
             case err: Throwable         =>
               // Logging only unanticipated errors, not related to Block API or input parsing (user errors)
-              Log[F].error("HTTP API response error", err) *> BadRequest(err.getMessageSafe.asJson)
+
+              // To indicate that error is not related to internal node error and node can continue running,
+              // the stack is cleared and error logged as a warning.
+              Sync[F].delay(err.setStackTrace(Array.empty[StackTraceElement])) *>
```
Comment (tgrospic) [inline node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala]: Why is the reason to clear stack trace?

File: shared/src/main/scala/coop/rchain/store/LmdbKeyValueStore.scala [hunk 2]
```diff
@@ -58,7 +58,13 @@ final case class LmdbKeyValueStore[F[_]: Sync](
   // GET
   override def get[T](keys: Seq[ByteBuffer], fromBuffer: ByteBuffer => T): F[Seq[Option[T]]] =
     withTxnSingleThread(isWrite = false) { (txn, dbi) =>
-      keys.map(x => Option(dbi.get(txn, x)).map(fromBuffer))
+      keys.map(
+        x =>
+          Try(dbi.get(txn, x))
+            .collect { case null => throw new Exception("Not found"); case b: ByteBuffer => b }
+            .toOption
+            .map(fromBuffer)
```
Comment (tgrospic) [inline shared/src/main/scala/coop/rchain/store/LmdbKeyValueStore.scala]: `Option(null) == None` is wrapping null value to Option.

With `Try(...).toOption` we are basically swallowing any exception to None.

Please refer to this issue how to handle exceptions.
- #3769

File: node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala (hunk 1 above)
Comment (stanislavlyalin) [reply node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala]: This is related to your [comment](https://github.com/rchain/rchain/issues/3740#issuecomment-1158930726).
image
It is looks like usual log message, not a fatal error.
But now I'm thinking it is output just for node admin, not for client, so it is better to provide maximum information about error.

Comment (tgrospic) [reply node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala]: Yes, exactly. Especially because this is unexpected API error which is not fatal, but node operator should pay some attention and report upstream.

File: shared/src/main/scala/coop/rchain/store/LmdbKeyValueStore.scala (hunk 2 above)
Comment (stanislavlyalin) [reply shared/src/main/scala/coop/rchain/store/LmdbKeyValueStore.scala]: > `Option(null) == None` is wrapping null value to Option.
> 
> With `Try(...).toOption` we are basically swallowing any exception to None.
> 
> Please refer to this issue how to handle exceptions.
> 
>     * [Strategy, categorization and handling exceptions #3769](https://github.com/rchain/rchain/issues/3769)

We shouldn't swallow exceptions, I agree. But in that case we should change interface of `KeyValueStore.get` to return sequence of `Either` or `Try` and all of three derivations.

I think returning `None` from `get` when something goes wrong is expected behavior.

Comment (tgrospic) [reply shared/src/main/scala/coop/rchain/store/LmdbKeyValueStore.scala]: We don't want to handle errors in any way and leave errors to _bubble up_ in higher layers where we want to decide what is appropriate action.

Comment (stanislavlyalin) [reply shared/src/main/scala/coop/rchain/store/LmdbKeyValueStore.scala]: Higher layer is `WebApiRoutes.scala` in that case. It is Ok to print exception with stack trace as is for admin. But how to convert this exception to something meaningful for client?

Comment (tgrospic) [reply shared/src/main/scala/coop/rchain/store/LmdbKeyValueStore.scala]: We want to prevent this exception, so input data casing the error should be validated.

File: node/src/main/scala/coop/rchain/node/web/Transaction.scala [hunk 3]
```diff
@@ -149,7 +149,7 @@ final case class CacheTransactionAPI[F[_]: Concurrent](
   private val blockDeferMap: TrieMap[String, Deferred[F, TransactionResponse]] = TrieMap.empty
 
   def getTransaction(blockHash: String): F[TransactionResponse] =
-    store.get1(blockHash) >>= { transactionOpt =>
+    (if (blockHash.isEmpty) None.pure else store.get1(blockHash)) >>= { transactionOpt =>
```
Comment (tgrospic) [inline node/src/main/scala/coop/rchain/node/web/Transaction.scala]: 1. What will be executed when block hash is empty? Do we want to execute anything?
1. Is it the same to not have transaction for some input or exit early because of invalid input (which cannot have transactions at all)?

NOTE: The purpose of this PR is not to hide the error.

File: node/src/main/scala/coop/rchain/node/api/WebApi.scala [hunk 4]
```diff
@@ -119,7 +120,10 @@ object WebApi {
       blockApi.isFinalized(hash).flatMap(_.liftToBlockApiErr)
 
     def getTransaction(hash: String): F[TransactionResponse] =
-      cacheTransactionAPI.getTransaction(hash)
+      OptionT
+        .whenF(hash.nonEmpty)(cacheTransactionAPI.getTransaction(hash))
+        .value
+        .flatMap(_.liftTo(new Exception("Block hash cannot be empty.")))
```
Comment (tgrospic) [inline node/src/main/scala/coop/rchain/node/api/WebApi.scala]: Nice solution!

Here we want to throw `BlockApiException` which will not be logged because it's related to invalid user input.

File: node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala [hunk 5]
```diff
@@ -36,7 +36,11 @@ object WebApiRoutes {
             case err: BlockApiException => BadRequest(err.getMessageSafe.asJson)
             case err: Throwable         =>
               // Logging only unanticipated errors, not related to Block API or input parsing (user errors)
-              Log[F].error("HTTP API response error", err) *> BadRequest(err.getMessageSafe.asJson)
+              // To indicate that error is not related to internal node error and
+              // node can continue running, error logged as a warning.
+              Log[F].warn("HTTP API response error") *>
+                Sync[F].delay(err.printStackTrace()) *>
```
Comment (tgrospic) [inline node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala]: Please add overload to `warn` method accepting Throwable similar how it's defined for `error` method.
Also _cause_ should be defined as a thunk the same as the message.
https://github.com/rchain/rchain/blob/76f14c516bac3d6be2f91318c9b202b4239465bb/shared/src/main/scala/coop/rchain/shared/Log.scala#L38-L46

**Review by zsluedem — APPROVED** [review]
LGTM

File: node/src/main/scala/coop/rchain/node/api/WebApi.scala [hunk 6]
```diff
@@ -119,7 +120,10 @@ object WebApi {
       blockApi.isFinalized(hash).flatMap(_.liftToBlockApiErr)
 
     def getTransaction(hash: String): F[TransactionResponse] =
-      cacheTransactionAPI.getTransaction(hash)
+      OptionT
+        .whenF(hash.nonEmpty)(cacheTransactionAPI.getTransaction(hash))
+        .value
+        .flatMap(_.liftTo(new BlockApiException("Block hash cannot be empty.")))
```
Comment (tgrospic) [inline node/src/main/scala/coop/rchain/node/api/WebApi.scala:126]: I didn't realize this the first time, but now exception for empty hash will be thrown even for correct hash which is not available in transaction API.

I found pattern with Option#filter to be concise solution in these situations.
```scala
Option(hash)
  .filter(_.nonEmpty)
  .liftTo(new BlockApiException("Block hash cannot be empty."))
  .flatMap(cacheTransactionAPI.getTransaction)
```

Comment (stanislavlyalin) [reply node/src/main/scala/coop/rchain/node/api/WebApi.scala:126]: @tgrospic, are you sure? I checked this case
image

`OptionT.whenF(hash.nonEmpty)(cacheTransactionAPI.getTransaction(hash)).value` returns `None` if hash is empty or `Some(cacheTransactionAPI.getTransaction(hash))` otherwise.

Comment (tgrospic) [reply node/src/main/scala/coop/rchain/node/api/WebApi.scala:126]: ~~And for correct hash when `cacheTransactionAPI.getTransaction` returns None?~~

Oh, sorry. I was thinking that `getTransaction` returns value in an Option.

Comment (stanislavlyalin) [reply node/src/main/scala/coop/rchain/node/api/WebApi.scala:126]: WDY mean _correct hash_? `cacheTransactionAPI.getTransaction` cannot returns None because its returns  type is `F[TransactionResponse]`.

**Review by tgrospic — APPROVED** [review]
LGTM

**Comment by stanislavlyalin** [comment]
bors merge
