### PR TITLE
Fix tests for block merge branch + misc leftover

### LINKED ISSUE #3277: Collection of issues left over from block-merge sync to dev branch
- ~~redesign proposer state~~ done in https://github.com/rchain/rchain/pull/3312
- ~~address minor comments~~ done in https://github.com/rchain/rchain/pull/3312
- reimplement tests disabled in <https://github.com/rchain/rchain/pull/3201/commits/53578aa8c579b434eee256f7971143fcc62d68c7>, if applicable
- ~~fix all tests~~ done in https://github.com/rchain/rchain/pull/3312

### PR DESCRIPTION
**Pull request by nzpr**
## Overview
This PR aims restoring all tests disabled in block-merge branch, as well as address minor comments on merge `block-merge` feature branch.

### CODE REVIEW

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala [hunk 1]
```diff
@@ -90,88 +91,96 @@ class MultiParentCasperCommunicationSpec extends FlatSpec with Matchers with Ins
...
-//          _ = nodes(1).logEff.infos.count(_ startsWith "Requested missing block") should be(10)
-//          result = nodes(0).logEff.infos.count(
-//            s => (s startsWith "Received request for block") && (s endsWith "Response sent.")
-//          ) should be(10)
-//          // Oh yes - 10!
-//        } yield result
-//      }
-//  }
+  // TODO this test fails because `TestNode.propagate(nodes)` returns prematurely.
+  it should "ask peers for blocks it is missing and add them" ignore effectTest {
```
Comment (nzpr) [inline casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: this test is ignored, because it looks like TestNode.propagate(nodes) returns prematurely in presence of async message processing. Im not sure yet whats the way to fix this.

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala [hunk 2]
```diff
@@ -14,55 +15,55 @@ import org.scalatest.{FlatSpec, Inspectors, Matchers}
...
+        //1 receives request for has block1; sends i have block1
+        //2 receives I have block1; asks for block1
+        //1 receives request block1; sends block1
+        //2 receives block2; asks for block1
+        //2 receives block1; adds both block1 and block2
+
+        // due to asynchronous processing of blocks syncWith ends before blocks are added to DAG
+        // as this test is supposed to check that node is asking for block, just checking blockstore
+        // for presence of block is enough
+        _ <- nodes(2).blockStore.contains(signedBlock1.blockHash) shouldBeF true
```
Comment (nzpr) [inline casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: this is fix for this tests, ptal at comment

File: casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala [hunk 3]
```diff
@@ -1,247 +1,229 @@
...
+
+    override def postCondition(state: State, result: Try[Result]): Prop = isValidAndNoErrors(result)
+  }
+
+  case class DeployAndPropose(node: RNode) extends Command {
+    override type Result = (ValidBlockProcessing, List[String])
+
+    override def run(sut: Sut): Result = {
+      val validator = sut.nodes(node.idx).node
+      val result = (deploy(validator, deployment(0)) >> create(validator) >>= (
```
Comment (nzpr) [inline casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala:190]: this test required sync version of propose

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala [hunk 4]
```diff
@@ -46,39 +46,6 @@ class MultiParentCasperMergeSpec extends FlatSpec with Matchers with Inspectors
     }
   }
 
-  // TODO enable tests below
```
Comment (nzpr) [inline casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala:49]: this does not make sense in presence of new MergeSpec. We can fix it but it'll require changes to some MergeSpec API (`merges(lookup, lookup, setup)`) is not present anymore. I don't think it worth it. We have BranchMergerSpec to merge actual blocks with cost accounting and StateMergeSpec to check all mergeability rules.

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala [hunk 5]
```diff
@@ -208,62 +175,4 @@ class MultiParentCasperMergeSpec extends FlatSpec with Matchers with Inspectors
       } yield ()
     }
   }
-
-//  "This spec" should "cover all mergeability cases" in {
```
Comment (nzpr) [inline casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala:212]: this is superseded by MergeSpec

File: casper/src/main/scala/coop/rchain/casper/storage/RNodeKeyValueStoreManager.scala [hunk 6]
```diff
@@ -62,7 +61,6 @@ object RNodeKeyValueStoreManager {
       (Db("eval-roots"), evalHistoryEnvConfig),
       (Db("eval-cold"), evalColdEnvConfig),
       // RSpace cache (used for block merge)
-      (Db("rspace-channels"), rspaceCacheEnvConfig),
```
Comment (nzpr) [inline casper/src/main/scala/coop/rchain/casper/storage/RNodeKeyValueStoreManager.scala]: this is duplicate for `channels` and not used

File: casper/src/test/scala/coop/rchain/casper/engine/RunningHandleBlockMessageSpec.scala [hunk 7]
```diff
@@ -1,134 +0,0 @@
-package coop.rchain.casper.engine
```
Comment (nzpr) [inline casper/src/test/scala/coop/rchain/casper/engine/RunningHandleBlockMessageSpec.scala:1]: There should be BlockProcessor test instead of this... I guess I need to write one

File: casper/src/main/scala/coop/rchain/casper/blocks/proposer/ProposeResult.scala [hunk 8]
```diff
@@ -24,7 +24,10 @@ case object NotEnoughNewBlocks         extends CheckProposeConstraintsFailure
 case object TooFarAheadOfLastFinalized extends CheckProposeConstraintsFailure
 
 object CheckProposeConstraintsResult {
-  def success: CheckProposeConstraintsResult = CheckProposeConstraintsSuccess
+  def success: CheckProposeConstraintsResult                    = CheckProposeConstraintsSuccess
+  def notBonded: CheckProposeConstraintsResult                  = NotBonded
+  def notEnoughNewBlock: CheckProposeConstraintsResult          = NotEnoughNewBlocks
+  def tooFarAheadOfLastFinalized: CheckProposeConstraintsResult = TooFarAheadOfLastFinalized
```
Comment (zsluedem) [inline casper/src/main/scala/coop/rchain/casper/blocks/proposer/ProposeResult.scala:30]: these methods are more like renaming from my perspective. I am curious why we need these methods.

File: casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala [hunk 9]
```diff
@@ -1,247 +1,229 @@
...
+  implicit def noShrink[T]: Shrink[T] = Shrink.shrinkAny
+  property("network") = HashSetCasperSpecification.property()
+}
+
+object HashSetCasperPropertiesApp {
+  def main(args: Array[String]): Unit =
+    HashSetCasperSpecification.property().check(_.withMinSuccessfulTests(1))
+}
+
+class NodeBox(val node: TestNode[Effect], var lastBlock: Option[BlockMessage]) {
```
Comment (zsluedem) [inline casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala:39]: Just curious that can we use `val` instead of `var`?

File: casper/src/main/scala/coop/rchain/casper/storage/RNodeKeyValueStoreManager.scala (hunk 6 above)
Comment (tgrospic) [reply casper/src/main/scala/coop/rchain/casper/storage/RNodeKeyValueStoreManager.scala]: Do we have this fixed on some other place? Channels map DB should not be shared with evaluator.

Channels map DB in Casper RSpace should be in the `rspace` folder with other DBs and for evaluator we can use dummy DB to not create any mark on disk.

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala [hunk 10]
```diff
@@ -14,55 +15,55 @@ import org.scalatest.{FlatSpec, Inspectors, Matchers}
 // casper and communication has little to do with each other, so commented out
```
Comment (tgrospic) [inline casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: Is this comment still relevant?

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala (hunk 2 above)
Comment (tgrospic) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: This test doesn't check what it says in the title, it only checks that node 2 will eventually receive block 1.

Can we check that BlockRetriever received a request from Casper  for block 1 (to not go further to TransportLayer)?

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala [hunk 11]
```diff
@@ -14,55 +15,55 @@ import org.scalatest.{FlatSpec, Inspectors, Matchers}
...
+              for {
+                maybeBlock1 <- node.blockStore.get(signedBlock1.blockHash)
+                maybeBlock2 <- node.blockStore.get(signedBlock2.blockHash)
+              } yield {
+                withClue(s"Assertion failed for node ${node.local} --") {
+                  maybeBlock1 shouldBe Some(signedBlock1)
+                  maybeBlock2 shouldBe Some(signedBlock2)
+                }
+              }
+            }*/
```
Comment (tgrospic) [inline casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: Is there a reason to keep this comment out part?

**Comment by tgrospic** [comment]
Please address in this PR fix mentioned in https://github.com/rchain/rchain/pull/3351/files#r592805237 about  the result from last finalized height constraint checker.

File: casper/src/main/scala/coop/rchain/casper/storage/RNodeKeyValueStoreManager.scala (hunk 6 above)
Comment (tgrospic) [reply casper/src/main/scala/coop/rchain/casper/storage/RNodeKeyValueStoreManager.scala]: Changes in PR #3367 (https://github.com/rchain/rchain/pull/3367/commits/fe7821a3bab32abea7ff361c312acd3582209a84) should cover this fix so not needed here.

File: casper/src/main/scala/coop/rchain/casper/blocks/proposer/ProposeResult.scala (hunk 8 above)
Comment (nzpr) [reply casper/src/main/scala/coop/rchain/casper/blocks/proposer/ProposeResult.scala:30]: I made this to be able to assert in tests `assert(r == ProposeResult.notEnoughBlocks && b.isEmpty)`
It does not work with case objects

File: casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala (hunk 9 above)
Comment (nzpr) [reply casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala:39]: slowcooker is not executed I guess, and this is very old code. I think not worth looking into

**Comment by nzpr** [comment]
> Please address in this PR fix mentioned in https://github.com/rchain/rchain/pull/3351/files#r592805237 about the result from last finalized height constraint checker.

This is fix ^

File: casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala (hunk 9 above)
Comment (zsluedem) [reply casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala:39]: We can consider removing it later and come up with other plans for that purpose.

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala (hunk 11 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: Its old leftover, I'll remove it

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala (hunk 2 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: https://github.com/rchain/rchain/pull/3355/commits/00eb5badd57112a8e68e41498402476caf77db2a

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala (hunk 10 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: No, removed https://github.com/rchain/rchain/pull/3355/commits/00eb5badd57112a8e68e41498402476caf77db2a

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala (hunk 11 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: https://github.com/rchain/rchain/pull/3355/commits/00eb5badd57112a8e68e41498402476caf77db2a

**Comment by nzpr** [comment]
Hm... one integration test is failing because of this https://github.com/rchain/rchain/pull/3355/commits/fe7bac71b2cc8199467f606af528db99d4a85113. Let me check

File: casper/src/main/scala/coop/rchain/casper/blocks/proposer/Proposer.scala [hunk 12]
```diff
@@ -84,18 +84,23 @@ class Proposer[F[_]: Concurrent: Log: Span](
...
-    val work = Stream(s1, s2, s3)
-    work
-      .parJoin(3)
-      .compile
-      .toList
-      // pick some result that is not Success, or return Success
-      .map(_.find(_ != CheckProposeConstraintsSuccess).getOrElse(CheckProposeConstraintsSuccess))
-  }
+  ): F[CheckProposeConstraintsResult] =
+    checkActiveValidator(s, validator) match {
```
Comment (nzpr) [inline casper/src/main/scala/coop/rchain/casper/blocks/proposer/Proposer.scala:102]: As sync constraints depend on last message - for not bonded validators there is no such message. So first we check bonding and then check constraint, that might rise an error if no latest message for bonded validator found.

File: casper/src/test/scala/coop/rchain/casper/engine/RunningHandleBlockMessageSpec.scala (hunk 7 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/engine/RunningHandleBlockMessageSpec.scala:1]: I suggest first to address concurrent block processing performance https://github.com/rchain/rchain/issues/3346 and then get back to writing tests

File: casper/src/test/scala/coop/rchain/casper/addblock/ProposerSpec.scala [hunk 13]
```diff
@@ -0,0 +1,227 @@
...
+import coop.rchain.models.BlockHash.BlockHash
+import coop.rchain.models.blockImplicits.getRandomBlock
+import coop.rchain.shared.Log
+import monix.eval.Task
+import monix.execution.Scheduler.Implicits.global
+import org.scalatest.{FlatSpec, Matchers}
+
+import scala.collection.immutable.HashMap
+
+class ProposerSpec extends FlatSpec with Matchers with BlockDagStorageFixture {
```
Comment (zsluedem) [inline casper/src/test/scala/coop/rchain/casper/addblock/ProposerSpec.scala:25]: ~~Hm.....I don't know how to put this. The tests here seem to test themselves instead of testing something very important in production. I used to write tests like these in other projects.~~

Comment (zsluedem) [reply casper/src/test/scala/coop/rchain/casper/addblock/ProposerSpec.scala:25]: Oh. Nvm. I missed something. They are actually good.

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala [hunk 14]
```diff
@@ -46,39 +46,6 @@ class MultiParentCasperMergeSpec extends FlatSpec with Matchers with Inspectors
...
   }
 
-  // TODO enable tests below
-//  it should "handle multi-parent blocks correctly when they operate on stdout" in effectTest {
-//    def echoContract(no: Int) =
-//      Rho(s"""new stdout(`rho:io:stdout`) in { stdout!("Contract $no") }""")
-//    merges(echoContract(1), echoContract(2), Rho("Nil"))
-//  }
-//
-//  it should "not conflict on registry lookups" in effectTest {
```
Comment (zsluedem) [inline casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala:56]: I think this one is still a worthy one. We can create another issue seperate for that.

Comment (zsluedem) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala:56]: This can be extended to our base rholang library and see what would cause conflicts.

File: casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala [hunk 15]
```diff
@@ -1,247 +1,229 @@
...
+  def update(bm: Option[BlockMessage]): Unit = this.lastBlock = bm
+}
+
+object HashSetCasperActions {
+  import GenesisBuilder._
+
+  def context(
+      amount: Int,
+      bondsGen: Seq[PublicKey] => Map[PublicKey, Long]
```
Comment (zsluedem) [inline casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala]: `bondsGen` is not used.

File: casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala [hunk 16]
```diff
@@ -1,247 +1,229 @@
...
+  ): GenesisContext = {
+    val genesis =
+      buildGenesis(amount)
+    genesis
```
Comment (zsluedem) [inline casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala]: the expression here can be simplified.

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala [hunk 17]
```diff
@@ -90,88 +70,96 @@ class MultiParentCasperCommunicationSpec extends FlatSpec with Matchers with Ins
...
+        // this block will be propagated to all nodes and force nodes(2) to ask for missing blocks.
+        br <- makeDeploy(0) >>= (nodes(0).addBlock(_)) // block h1
+
+        _ <- TestNode.propagate(nodes) // force the network to communicate
+
+        _ <- nodes(2).contains(br.blockHash) shouldBeF true
+
+        nr <- makeDeploy(0) >>= (nodes(2).addBlock(_))
+      } yield {
+        PrettyPrinter.buildString(nr.header.parentsHashList) shouldBe PrettyPrinter
```
Comment (zsluedem) [inline casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: `buildString` would truncate the whole message which can be a problem in some extreme cases. Maybe `buildStringNoLimit` or just compare the hashes

File: casper/src/test/scala/coop/rchain/casper/addblock/ProposerSpec.scala [hunk 18]
```diff
@@ -0,0 +1,227 @@
...
+            val p = new Proposer[Task](
+              validateBlock = alwaysSuccesfullValidation,
+              checkFinalizedHeight = okProposeConstraint,
+              checkActiveValidator = alwaysActiveF,
+              checkEnoughBaseStake = okProposeConstraint,
+              getCasperSnapshot = getCasperSnapshotF,
+              createBlock = createBlockF,
+              proposeEffect = proposeEffect(10),
+              validator = dummyValidatorIdentity
+            )
```
Comment (tgrospic) [inline casper/src/test/scala/coop/rchain/casper/addblock/ProposerSpec.scala:215]: Code for creating Proposer is almost identical in all tests. This should be extracted in separate function so only different parts are specified in each test. I'm ok with this now because we will change Proposer anyway.

File: casper/src/test/scala/coop/rchain/casper/engine/RunningHandleBlockMessageSpec.scala (hunk 7 above)
Comment (tgrospic) [reply casper/src/test/scala/coop/rchain/casper/engine/RunningHandleBlockMessageSpec.scala:1]: Please update #3346 with this info and/or create new issue for block processor tests.

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala (hunk 1 above)
Comment (tgrospic) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: In async version we have Deferred to be able to wait on propose to complete. Why we cannot use it here?

File: casper/src/main/scala/coop/rchain/casper/blocks/proposer/ProposeResult.scala (hunk 8 above)
Comment (tgrospic) [reply casper/src/main/scala/coop/rchain/casper/blocks/proposer/ProposeResult.scala:30]: I think you are pointing to another class ProposeResult.

But the reason is not case object because the same is with case classes. It's about unifying the type, in this example each constructor has a function returning `CheckProposeConstraintsResult`.

File: casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala [hunk 19]
```diff
@@ -1,265 +0,0 @@
-package coop.rchain.casper.api
```
Comment (tgrospic) [inline casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala:1]: Are there replacement tests for create block API?

File: casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala (hunk 9 above)
Comment (tgrospic) [reply casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala:39]: > slowcooker is not executed I guess, and this is very old code. I think not worth looking into

We should be careful in assessing the existing code, just because it's old is not a reason to be ignored or abandon it.

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala (hunk 1 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: propagate uses `.handleReceive()` which is just adding block to the queue. Previously `.handleReceive()` was blocking until block is processed.

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala (hunk 17 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: Nice catch, I agree. I don't like comparing just hashes because in case of test failure it does not print valuable information - what the hashes are actually, only non readable byte string.

File: casper/src/test/scala/coop/rchain/casper/engine/RunningHandleBlockMessageSpec.scala (hunk 7 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/engine/RunningHandleBlockMessageSpec.scala:1]: https://github.com/rchain/rchain/issues/3346#issuecomment-818549965

File: casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala (hunk 9 above)
Comment (nzpr) [reply casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala:39]: It was not compiling due to changes in block merge branch, so I commented that out temporarily. This PR adds minor fixes for it to compile. Might be I should use /* ... */ comments style for that, so its more clear what has been changed actually

File: casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala (hunk 15 above)
Comment (nzpr) [reply casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala]: It's old code and not used, do you want me to fix it or leave it as it is?

File: casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala (hunk 16 above)
Comment (nzpr) [reply casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala]: It's old code and not used, do you want me to fix it or leave it as it is?

File: casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala (hunk 19 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala:1]: https://github.com/rchain/rchain/blob/34146e9a8f29cd49fe2a814ba7d0a78fe5f69bd6/casper/src/test/scala/coop/rchain/casper/addblock/ProposerSpec.scala#L25 is the replacement

File: casper/src/test/scala/coop/rchain/casper/addblock/ProposerSpec.scala (hunk 18 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/addblock/ProposerSpec.scala:215]: Just a general remark related to this - as we were discussing general approach to building logic inside pure state. Though I agree this might be extracted to dedicated function, still we need to override quite a lot, so not sure it will gain benefit. To me its like testing an equation -  you pass in variables and look at the output, having ability to set some defaults for variables in this equation tells that you might not even need this variables. 
But yes, I did not think a lot which values for functions are used in all or most tests, might be there is a room for shrinking the code.

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala (hunk 17 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: https://github.com/rchain/rchain/pull/3355/commits/fe99286a4e6aade733a95e754960f688475dc21e

File: casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala (hunk 16 above)
Comment (nzpr) [reply casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala]: https://github.com/rchain/rchain/pull/3355/commits/fe99286a4e6aade733a95e754960f688475dc21e

File: casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala (hunk 15 above)
Comment (nzpr) [reply casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala]: https://github.com/rchain/rchain/pull/3355/commits/fe99286a4e6aade733a95e754960f688475dc21e

**Comment by nzpr** [comment]
Tests were not compiling, odd because its working locally. Rebased on recent feature branch, lets see.

**Comment by nzpr** [comment]
@tgrospic @zsluedem I guess I've addressed all  comments

File: casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala (hunk 9 above)
Comment (tgrospic) [reply casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala:39]: Yeah, block comments should be better in this case. I tried running this test on dev branch but it's failing there also. We need to check if it make sense to fix it or if it's not needed anymore.

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala (hunk 17 above)
Comment (tgrospic) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: What is printed is whatever is returned on calling `.toString` on that object. We can create override of `toString` to customize  friendly string representation which is also useful in debugging.
I'm not sure if ScalaTest have some other way to do it e.g. using cats with Show instances which would be more elegant solution.

File: casper/src/test/scala/coop/rchain/casper/addblock/ProposerSpec.scala (hunk 18 above)
Comment (tgrospic) [reply casper/src/test/scala/coop/rchain/casper/addblock/ProposerSpec.scala:215]: Here is simplified example of what I mean. With the _truthTable_ we immediately see what is tested and what results we expect.

```scala
def doSomethind(a: Int, b: String, c: List[Int]) = ???

val r1 = doSomething(1, "First", List(42))
val r2 = doSomething(2, "Second", List(42))
val r3 = doSomething(3, "Third", List(42))

assert(r1 == 11)
assert(r2 == 12)
assert(r3 == 13)

// Instead we can recognize what input and output we want to compare.
val truthTable = List(
  (1, "First", 11),
  (2, "First", 12),
  (3, "First", 13),
)
// And how it's called is not important and can be written only once.
truthTable.map((arg1, arg2, result) => assert(doSomething(arg1, arg2, List(42)) == result))
```

File: casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala (hunk 19 above)
Comment (tgrospic) [reply casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala:1]: I don't see that BlockAPI is used at all in Proposer tests. I'm I missing something?

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala (hunk 1 above)
Comment (tgrospic) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: I'm not sure what are you suggesting. Should we fix this test later or it's not needed anymore because it's replaced by some other test?

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala (hunk 4 above)
Comment (tgrospic) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala:49]: Do we have test with stdout and registry lookup when checking *all mergeability rules*?

File: casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala (hunk 19 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala:1]: I believe how CreateBlockAPITest is written - it is a test for proposer logic not for API. We might write another test for blockAPI to test if it is returning valid responses. Maybe do this after this <https://github.com/rchain/rchain/blob/956680dbef1063e518912405f909618be28d0570/casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala#L118-L120>?

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala (hunk 14 above)
Comment (zsluedem) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala:56]: https://github.com/rchain/rchain/issues/3381

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala (hunk 1 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: I think we should replace this test. Basically it is an integration test which ensures that 1) node will add dependencies to block retriever 2) block addition will trigger processing of pendent descendants 3) casper can validate block. Test for 3) already exist, test for 1 is in the same file. We can modify this particular test to check if dependencies are actually received and are in casper buffer. I've added commit for that https://github.com/rchain/rchain/pull/3355/commits/e52588e3cc1d55504429c51e08479c9d00fdf5f4

The remainder is logic for 2), which is now implemented in `node` project. I'm not sure what's the best way to do that - I'm thinking to look into concurrent block processing and maybe after that check this test.

File: casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala (hunk 19 above)
Comment (tgrospic) [reply casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala:1]: No doubt we need to redefine block API. I'm ok to leave this as part of those changes.

File: casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala (hunk 1 above)
Comment (tgrospic) [reply casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala]: OK, let's keep it in reduced form.

**Review by tgrospic — APPROVED** [review]
LGTM
