### PR TITLE
Fixed method to find BlockHash by truncated string with odd length

### LINKED ISSUE #3495: Implement `getBlock` by hash via DAG representation (dagSet).
## Overview

Currently we iterate over all records when block hash is searched with prefix (`BlockStore#find`). This is slow because hashes are read from LMDB database via BlockStore implementation.

We have in `DagBlockRepresentation` all block hashes in memory to do the same operation much much faster.

## Solution

Implement search for a block with block hash prefix with `BlockDagRepresentation`.

EDIT: Extend `BlockDagRepresentation` with the method to find complete hash from hash prefix and use it directly in `BlockAPI`.

### PR DESCRIPTION
**Pull request by stanislavlyalin**
## Overview
Fix #3495.

If `truncatedHash` is **odd** length string we cannot convert it to `ByteString` with **8 bit** resolution because each symbol has **4 bit** resolution. Need to make a string of **even** length by removing the last symbol, then find all the matching hashes and choose one that matches the full `truncatedHash` string.

## Performance results
Hash to search: **1234abcd** (actually doesn’t exist)

|machine|averaged request time|factor|
|---|---|---|
| Test net observer | 1.66 sec | 20.75x |
| Current (de1a.dev.rchain.coop) | ~80 ms | 1x |

**1234abcd** (even) vs **1234abc** (odd) on locally running node

| hash length | averaged request time | factor |
|---|---|---|
| even length (1234abcd) | ~48 ms | 1.14x |
| odd length (1234abc) | ~42 ms | 1x |

| node | find block request time | factor |
|---|---|---|
| Main net, node0 | ~10.2s | 102x |
| Main net, observer-us | ~100ms | 1x |

bors try

### CODE REVIEW

**Comment by stanislavlyalin** [comment]
bors try

File: block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala [hunk 1]
```diff
@@ -77,8 +78,21 @@ final class BlockDagKeyValueStorage[F[_]: Concurrent: Log] private (
...
+        // because each symbol has 4 bit resolution. Need to make a string of even length by removing the last symbol,
+        // then find all the matching hashes and choose one that matches the full truncatedHash string
+        val truncatedByteString =
+          ByteString.copyFrom(Base16.unsafeDecode(truncatedHash.dropRight(1)))
+        dagSet
+          .filter(hash => hash.startsWith(truncatedByteString))
+          .find(
+            hash => DatatypeConverter.printHexBinary(hash.toByteArray).startsWith(truncatedHash)
+          )
+      }
```
Comment (zsluedem) [inline block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala:91]: Interesting. Never thought of that. Good catch.

**Comment by stanislavlyalin** [comment]
bors try

File: block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala [hunk 2]
```diff
@@ -77,8 +77,20 @@ final class BlockDagKeyValueStorage[F[_]: Concurrent: Log] private (
...
+        dagSet.find(hash => hash.startsWith(truncatedByteString))
+      } else {
+        // if truncatedHash is odd length string we cannot convert it to ByteString with 8 bit resolution
+        // because each symbol has 4 bit resolution. Need to make a string of even length by removing the last symbol,
+        // then find all the matching hashes and choose one that matches the full truncatedHash string
+        val truncatedByteString = truncatedHash.dropRight(1).unsafeHexToByteString
+        dagSet
+          .filter(hash => hash.startsWith(truncatedByteString))
+          .find(
+            hash => Base16.encode(hash.toByteArray).startsWith(truncatedHash)
```
Comment (tgrospic) [inline block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala]: You can use extension function on ByteString also created by @zsluedem in PR [#3517 (ByteStringSyntax)](https://github.com/rchain/rchain/pull/3517/files#diff-b467c85b5271a3e0eb2832ed6e1d5a9c6764ef3f65b5e8cfd9a0c7a01a57a0b8R35).
Together with shorthand for argument (`_`) in anonymous functions it can be one liner.
```scala
dagSet
  .filter(_.startsWith(truncatedByteString))
  .find(_.toHexString.startsWith(truncatedHash))
```

Nice solution to resolve incomplete hex problem. :+1:

**Review by zsluedem — APPROVED** [review]
LGTM

**Review by tgrospic — APPROVED** [review]
LGTM

**Comment by stanislavlyalin** [comment]
bors merge
