### PR TITLE
Fix requesting blocks and state chunks

### LINKED ISSUE #3098: Testing of LFS
## Overview

This issue is to record several rounds of testing of **Last Finalized State** pre release versions. Tests are more performance oriented and some of the bug fixes and optimitations are done between each test setup.

Results are starting from the last setup. Shows how speed is increased with stronger machine. This is due to additonal computation needed for verification of the Rholang state (#3145). This is visible in high usage of CPU during sync.  

Another important factor is disk speed. All tests are done on SSD disks and on stronger machines faster speed reduces overall sync duration.

### Testing setup 4

This round is almost identical to _setup 3_ with additional optimization in receiving blocks (#3243) which include block sorting as part of download and with testing on 32 vCPU machine.

RNode Docker image version: [`rchain/rnode:v0.9.26-rc`](https://hub.docker.com/layers/rchain/rnode/v0.9.26-rc/images/sha256-af9d5c6467474eb6e47d1557dfdef26c312a5834eeb3fed5c94b8d6ce25a5ee9?context=explore)

| Nr. | Sync time<br>(fully catch up) | Sync Rholang state | Sync blocks | VPS | Log
| --- | ---        | ---    | ---    | ---                         | ---
| 1   | **2.25 h** | 1.5 h  | 1.75 h | 32vCPU 64GB (DigitalOcean)  | [test-4-do-32vcpu-64g.zip](https://github.com/rchain/rchain/files/5630012/test-4-do-32vcpu-64g.zip)
| 2   | **3.25 h** | 1.5 h  | 2 h    | 16vCPU 32GB CPX51 (Hetzner) | [test-4-cpx51-32g.zip](https://github.com/rchain/rchain/files/5630016/test-4-cpx51-32g.zip)
| 3   | **3 h**    | 1.75 h | 2 h    | 8vCPU 32GB (IBM)                   | [test-4-ibm-8vcpu-32g.zip](https://github.com/rchain/rchain/files/5630025/test-4-ibm-8vcpu-32g.zip)
| 4   | **4 h**    | 2.25 h | 2.5 h  | 8vCPU 16GB CPX41 (Hetzner)  | [test-4-cpx41-16g.zip](https://github.com/rchain/rchain/files/5630022/test-4-cpx41-16g.zip)
| 5   | **8 h**    | 4.5 h  | 3.5 h  | 4vCPU 8GB CPX31 (Hetzner)   | [test-4-cpx31-8g.zip](https://github.com/rchain/rchain/files/5630030/test-4-cpx31-8g.zip)

NOTE: CPU and memory observed in testing is the same as in setup 3, only overall duration is shorter.

[1] CPU, memory - 32vCPU 64GB (DigitalOcean)
test-4-do-32vcpu-64g-lfs-progress-cpu

### Testing setup 3

First two rounds of testing showed that LFS source node disk reading speed can make significant difference in overall speed for nodes to download Rholang state. In this testing setup,  to make reading from disk much faster RSpace folder on source node is converted to RAM disk which reduced reading from ~20sec to ~1sec for chunk of state sent over the network.

RNode Docker image version: [`tgrospic/rnode:v0.9.26-rc`](https://hub.docker.com/layers/tgrospic/rnode/v0.9.26-rc/images/sha256-85bb8d444b354b0628d871b561c2e908131f79cef880ece5b86678f64fb49195?context=repo)

NOTE: Bug with memory leak on network errors is still not resolved and one test with 8GB machine failed not listed in results.

| Nr. | Sync time<br>(fully catch up) | VPS
| --- | ---  | --- | 
| 1 | 4 hours (2.5 h blocks)<br>[test-3-cpx51-32g-full-ok-3.zip](https://github.com/rchain/rchain/files/5629935/test-3-cpx51-32g-full-ok-3.zip) | 16vCPU 32GB CPX51
| 2 | 5.5 hours (3.5 h blocks)<br>[test-3-cpx41-16g-full-ok-1.zip](https://github.com/rchain/rchain/files/5629947/test-3-cpx41-16g-full-ok-1.zip) | 8vCPU 16GB CPX41
| 3 | 9 hours (4.5 h blocks)<br>[test-3-cpx31-8g-full-ok-1.zip](https://github.com/rchain/rchain/files/5629957/test-3-cpx31-8g-full-ok-1.zip) | 4vCPU 8GB CPX31

#### Observations from testing

[1] CPU, memory - 16vCPU 32GB CPX51
test-3-cpx51-32g-lfs-progress-cpu

[1] Direct buffer - 16vCPU 32GB CPX51
test-3-cpx51-32g-lfs-progress-buffer

[2] CPU, memory - 8vCPU 16GB CPX41
test-3-16g-lfs-progress-cpu

[3] CPU, memory - 4vCPU 8GB CPX31
test-3-8g-lfs-progress-cpu

Survived network errors without crashing - 4vCPU 8GB CPX31
test-3-8g-lfs-progress-3-errors-cpu

### Testing setup 2

RNode Docker image version: [`tgrospic/rnode:v0.9.26-beta`](https://hub.docker.com/layers/tgrospic/rnode/v0.9.26-beta/images/sha256-0734a74f064939d43208d82c6914f64a0917b4de95cca0ae863a3999f2d53e3c?context=repo)

| Nr. | Source | Duration | Sync time<br>(fully catch up) | Environment
| --- | ---  | ---   | --- | ---
| 1 | Full  | 12.5 hours (2.5 h blocks) | - | One machine + 3 active nodes
| 2 | LFS  | ERROR interrupted<br>[rnode-restart-error.zip](https://github.com/rchain/rchain/files/5241197/rnode-restart-error.zip) | - | Target alone on another machine<br>(Docker on Hetzner cloud CPX31)
| 3 | LFS [2] | 4.5 hours (2.5 blocks)<br> [rnode-test-3.zip](https://github.com/rchain/rchain/files/5244082/rnode-test-3.zip) | 8 hours | Target alone on another machine<br>(Docker on Hetzner cloud CPX31)
| 4 | LFS [3] | 6 hours (2 blocks)<br> [rnode-test-4.zip](https://github.com/rchain/rchain/files/5248452/rnode-test-4.zip) | 10 hours | Target alone on another machine<br>(Docker on Hetzner cloud CX31)

#### Observations from testing

[3] After node received LFS, it's not responding to requests for tuple space (_StateItems_). After restart it works as expected.

[2] CPU, memory
image

[2] Direct buffer memory
image

### Testing setup 1

~Trie traversal is slow when number of records is bigger then 3,000 and it's rising faster then linear.~ Resolved in PR #3099.

Performance of LFS should be tested with this configuration.

RNode Docker image for all nodes: [`rchain/rnode:v0.9.26-alpha`](https://hub.docker.com/layers/rchain/rnode/v0.9.26-alpha/images/sha256-8dee109eb6bb377a8912111e09489ea105f926eb36d3d6a53e5195738d170d60?context=explore)

1. Observer node with full state
2. Observer node with empty state (bootstrap from `1.`)
3. Observer node with empty state (bootstrap from `2.`)

~Observer nodes with empty state (2. and 3.) must have higher limit for direct buffer memory to 3GB.
`-XX:MaxDirectMemorySize=3g`~
Memory leak with direct buffer is fixed in transport layer #3239 so now limit can be much lower.
`-XX:MaxDirectMemorySize=200m`

First operation is to test syncing of LFS from the full node. When this is done second syncing should use this node with _trimmed_ state as a source to sync the third node.

| Operation | Expected    | Measured
| ---       | ---         | ---
| 1. -> 2.  | 4-6 hours   | 7.5 hours (one machine + 1 active nodes)<br>11 hours (one machine + 4 active nodes)
| 2. -> 3.  | 1-3 hours   | 4 hours (one machine + 4 active nodes)

### LINKED ISSUE #3118: Node cannot request Approved block
When debugging LFS, sometimes it can be seen that node cannot receive approved block, thought it requested it.
In addition, there were issues with genesis ceremony tests failing randomly, when some genesis validators does not receive approved block.

With hight degree of confidence this is the fix for that. 
https://github.com/rchain/rchain/pull/3111/commits/872c6eb505bf1883727330dfdf8e568622d0a3ed
The problem is that `init` method of Casper Engine is being read before being initialised on Casper launch.
Won't create separate PR for that because fix is quite simple.

Duplicate issue reported
- #3320

### PR DESCRIPTION
**Pull request by tgrospic**
## Overview
This PR fixes and improves how block and state requester manage internal state to track received and saved items. Part of that is timeout stream which in previous solution was dequeueing twice so now Pipe is used instead to broadcast from the queue.

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

File: casper/src/main/scala/coop/rchain/casper/Estimator.scala [hunk 1]
```diff
@@ -123,11 +123,12 @@ final class Estimator[F[_]: Sync: Log: Metrics: Span](
...
     def hashParents(hash: BlockHash, lastFinalizedBlockNumber: Long): F[List[BlockHash]] =
       for {
-        currentBlockNumber <- blockDag.lookup(hash).map(_.get.blockNum)
-        result <- if (currentBlockNumber < lastFinalizedBlockNumber)
-                   List.empty[BlockHash].pure[F]
-                 else
-                   blockDag.lookup(hash).map(_.get.parents)
+        block              <- blockDag.lookupUnsafe(hash)
+        currentBlockNumber = block.blockNum
+        result = if (currentBlockNumber <= lastFinalizedBlockNumber)
```
Comment (nzpr) [inline casper/src/main/scala/coop/rchain/casper/Estimator.scala]: I think this is a valid change and it should be present, but now it breaks Estimator, when LCA is invalid block. 

As invalid block cannot be parent (it can only be a justification), it won't have children in the DAG. Because we add children looking at parents.
https://github.com/rchain/rchain/blob/0b160341a4826357e6521fed0371544ac3a5933d/block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockMetadataStore.scala#L67

So, when doing ranking, this code 
https://github.com/rchain/rchain/blob/633cd59bc1256a0c1d18424eef0537be9b8796c3/casper/src/main/scala/coop/rchain/casper/Estimator.scala#L165-L182
exits straight away


Want to reiterate that having old invalid block from slashed validator is questionable by itself, but looks like for now we don't touch this part.

So might be reverting this change makes sense for now. And to make LFS work - we have to download parents of the lowest required blocks as well.

Comment (tgrospic) [reply casper/src/main/scala/coop/rchain/casper/Estimator.scala]: Makes sense to download parents also for lowest of latest blocks.

I agree, invalid block in justification can be treated in a different way which can change which blocks need to be downloaded.

File: block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala [hunk 2]
```diff
@@ -147,11 +150,16 @@ final class BlockDagKeyValueStorage[F[_]: Concurrent: Log] private (
...
                   .map(_.validator)
                   .toSet
                   .diff(block.justifications.map(_.validator).toSet)
-                newValidatorsLatestMessages = newValidators.map(v => (v, block.blockHash))
+                bondingValidatorsLMs = bondingValidators.map(v => (v, block.blockHash))
+                // as we can add blocks in backwards (e.g. when reconstructing finalized state) -
+                // to ot overwrite existing LMs, we should have this check
+                newValidatorsLMs <- bondingValidatorsLMs.toList.filterA(
+                                     lm => latestMessagesIndex.contains(lm._1).not
+                                   )
```
Comment (tgrospic) [inline block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala]: This seems like another variant of the same check what is done with `seqNum` few lines below. Can we reuse the same logic to detect if latest message is already with highest seq number?

This can be simplified to use extension with only one key. 
`latestMessagesIndex.get(block.sender)`

Also it would be nice if seq number is kept as Option[Long] and used directly in check without introducing `0` as default.

Comment (nzpr) [reply block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala]: I think the overall `insert` method can be refactored, so was not doing any significant change. Should I make bigger refactoring hdy think?

Comment (tgrospic) [reply block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala]: I wanted to minimize changes in migration to LMDB but now it makes sense to refactor parts touched with the fix.

It also deserves separate PR to dev branch.

Comment (nzpr) [reply block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala]: https://github.com/rchain/rchain/pull/3123

File: casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala [hunk 3]
```diff
@@ -139,25 +139,11 @@ object ProtoUtil {
...
-      resultOpt <- blockParentOpt.traverse { bh =>
-                    dag.lookup(bh).map(_.get.weightMap.getOrElse(validator, 0L))
-                  }
-      result <- resultOpt match {
-                 case Some(result) => result.pure[F]
-                 case None         => dag.lookup(blockHash).map(_.get.weightMap.getOrElse(validator, 0L))
-               }
-    } yield result
-  }
+  ): F[Long] = dag.lookupUnsafe(blockHash).map(_.weightMap.getOrElse(validator, 0L))
```
Comment (tgrospic) [inline casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala]: @nzpr Do we still need this change?

File: casper/src/main/scala/coop/rchain/casper/Estimator.scala [hunk 4]
```diff
@@ -40,8 +40,11 @@ final class Estimator[F[_]: Sync: Log: Metrics: Span](
     Span[F].trace(Tips0MetricsSource) {
       for {
         latestMessageHashes <- dag.latestMessageHashes
-        _                   <- Span[F].mark("latest-message-hashes")
-        result              <- tips(dag, genesis, latestMessageHashes)
+        _ <- Log[F].info(s"latestMessages: \n ${latestMessageHashes
+              .map(lm => (PrettyPrinter.buildString(lm._1) + " -> " + PrettyPrinter.buildString(lm._2)))
+              .mkString("\n")}")
+        _      <- Span[F].mark("latest-message-hashes")
+        result <- tips(dag, genesis, latestMessageHashes)
```
Comment (tgrospic) [inline casper/src/main/scala/coop/rchain/casper/Estimator.scala]: @nzpr Do you want to leave these logging messages?

File: casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala [hunk 5]
```diff
@@ -178,37 +170,56 @@ class Initializing[F[_]
...
                        .tailRecM(loopDependencies)
       // Add sorted DAG in reverse order (from approved block)
       _ <- sortedHashes.flatMap(_._2).toList.reverse.traverse_ { hash =>
             for {
               block <- BlockStore[F].getUnsafe(hash)
-              _     <- BlockDagStorage[F].insert(block, invalid = false)
+              // if sender has stake 0 in approved block, this means that sender has been slashed and block is invalid
+              isInvalid = startBlock.body.state.bonds.exists(bond => {
+                bond.validator == block.sender && bond.stake == 0L
+              })
```
Comment (tgrospic) [inline casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala]: This seems to mark all blocks from slashed validator as invalid although only latest message should be invalid. :thinking:

File: casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala (hunk 3 above)
Comment (nzpr) [reply casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala]: I believe no

File: casper/src/main/scala/coop/rchain/casper/Estimator.scala (hunk 4 above)
Comment (nzpr) [reply casper/src/main/scala/coop/rchain/casper/Estimator.scala]: No, this is not needed

File: casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala (hunk 3 above)
Comment (tgrospic) [reply casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala]: Reverted.

File: casper/src/main/scala/coop/rchain/casper/Estimator.scala (hunk 4 above)
Comment (tgrospic) [reply casper/src/main/scala/coop/rchain/casper/Estimator.scala]: Reverted.

File: casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala (hunk 5 above)
Comment (tgrospic) [reply casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala]: Fixed.

**Review by 9rb — APPROVED** [review]
LGTM

File: casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala [hunk 6]
```diff
@@ -178,37 +170,60 @@ class Initializing[F[_]
...
 
     val emptySorted = SortedMap[Long, Set[BlockHash]]()
     for {
+      _ <- Log[F].info(s"Adding blocks for approved state to DAG.")
       sortedHashes <- (Seq(startBlock.blockHash), Set[BlockHash](), emptySorted)
                        .tailRecM(loopDependencies)
-      // Add sorted DAG in reverse order (from approved block)
-      _ <- sortedHashes.flatMap(_._2).toList.reverse.traverse_ { hash =>
+      // Latest messages from slashed validators / invalid blocks
+      slashedValidators = startBlock.body.state.bonds.filter(_.stake == 0L).map(_.validator)
```
Comment (nzpr) [inline casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala:205]: Nice!

File: casper/src/main/scala/coop/rchain/casper/Estimator.scala [hunk 7]
```diff
@@ -127,11 +127,12 @@ final class Estimator[F[_]: Sync: Log: Metrics: Span](
   ): F[Map[BlockHash, Long]] = {
     def hashParents(hash: BlockHash, lastFinalizedBlockNumber: Long): F[List[BlockHash]] =
       for {
-        currentBlockNumber <- blockDag.lookup(hash).map(_.get.blockNum)
-        result <- if (currentBlockNumber < lastFinalizedBlockNumber)
-                   List.empty[BlockHash].pure[F]
-                 else
-                   blockDag.lookup(hash).map(_.get.parents)
+        block              <- blockDag.lookupUnsafe(hash)
```
Comment (nzpr) [inline casper/src/main/scala/coop/rchain/casper/Estimator.scala]: Lets revert formatting as well, to not make an impression that there are changes to Estimator in PR

File: casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala [hunk 8]
```diff
@@ -537,6 +535,10 @@ class MultiParentCasperImpl[F[_]: Sync: Concurrent: Log: Time: SafetyOracle: Las
 }
 
 object MultiParentCasperImpl {
+
+  // TODO: Extract hardcoded deployLifespanBlocks from shard config
+  val deployLifespanBlocks = 50
```
Comment (nzpr) [inline casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala]: I suggest use just deployLifespan, as the only time measure we have is number of blocks

File: casper/src/main/scala/coop/rchain/casper/engine/LastFinalizedStateBlockRequester.scala [hunk 9]
```diff
@@ -72,24 +89,88 @@ object LastFinalizedStateBlockRequester {
...
     */
-  def stream[F[_]: Concurrent: Time: BlockDagStorage: BlockStore: CommUtil: Log](
+  def stream[F[_]: Concurrent: Time: BlockStore: CommUtil: Log](
       approvedBlock: ApprovedBlock,
       responseQueue: Queue[F, BlockMessage]
   ): F[Stream[F, Boolean]] = {
 
+    val block                           = approvedBlock.candidate.block
+    val approvedBlockNumber             = ProtoUtil.blockNumber(block)
+    val minBlockNumberForDeployLifespan = approvedBlockNumber - MultiParentCasperImpl.deployLifespanBlocks
```
Comment (nzpr) [inline casper/src/main/scala/coop/rchain/casper/engine/LastFinalizedStateBlockRequester.scala]: This safety range should have some name. Maybe DSR? deploy safety range? so this might be dsrBottomHeight? Im ok leaving this as it is, just think we need a name for this 50 blocks t cont are actually configurable

File: casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala [hunk 10]
```diff
@@ -536,8 +536,11 @@ class MultiParentCasperImpl[F[_]: Sync: Concurrent: Log: Time: SafetyOracle: Las
 
 object MultiParentCasperImpl {
 
-  // TODO: Extract hardcoded deployLifespanBlocks from shard config
-  val deployLifespanBlocks = 50
+  // TODO: Extract hardcoded deployLifespan from shard config
+  // Size of deploy safety range.
+  // Validators will try to put deploy in a block only for next `deployLifespan` blocks.
+  // Required to enable protection from re-submitting duplicate deploys
+  val deployLifespan = 50
```
Comment (tgrospic) [inline casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala:543]: Why to rename it? The number represents blocks but this is not part of the name.

Comment (nzpr) [reply casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala:543]: https://github.com/rchain/rchain/pull/3111#discussion_r489996773
`I suggest use just deployLifespan, as the only time measure we have is number of blocks`
I mean that we don't have any other measure for block lifespan besides blocks, we don't have wall clock or some else notion of time.

Comment (nzpr) [reply casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala:543]: And if make it deployLifespanBlocks - it still not fully disclose how this woks, because its actually block height. Node can propose more then 50 blocks, is some of them are on the same height and orphaned.
So the concept is quite complex, we cannot express everything in name, so better make it short.

File: casper/src/main/scala/coop/rchain/casper/Estimator.scala (hunk 7 above)
Comment (tgrospic) [reply casper/src/main/scala/coop/rchain/casper/Estimator.scala]: Makes sense.

**Comment by nzpr** [comment]
^ This force push reverts changes to estimator and removes commit with engine init fix. I'll create another PR for that.

File: casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala (hunk 10 above)
Comment (tgrospic) [reply casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala:543]: Fair points. But I don't think is that complex. It's just an optimization to check only some deploys for signature and not all until genesis.
Property `valid after block number` should be always part of the explanation which specify the limit in which blocks deploy can be used as **valid** deploy.

**Review by nzpr — APPROVED** [review]
