### PR TITLE
Hotstore rewrite (tuple space hash mismatch fix)

### LINKED ISSUE #3200: Problem with use of peek in NonNegativeNumber.rho
https://github.com/rchain/rchain/blob/0fb0c616dadb553b7b1bea09e448e7a0e1ff9765/casper/src/main/resources/NonNegativeNumber.rho#L48-L50

### PR DESCRIPTION
**Pull request by zsluedem**
## Overview

rebase the work in https://github.com/rchain/rchain/pull/3270 to the latest dev.

The original pr is intended to fix hotstore error which would cause tuple space mismatch

- [x] create a companion object of `HotStoreState`

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala [hunk 1]
```diff
@@ -32,261 +34,388 @@ trait HotStore[F[_], C, P, A, K] {
...
+                }
+              } else (state.copy(joins = state.joins.updated(channel, curJoins)), false)
+            })
+//      _ <- Sync[F]
+//            .raiseError(
+//              new IndexOutOfBoundsException(
+//                s"Index out of bounds when removing join"
+//              )
+//            )
+//            .whenA(err)
```
Comment (zsluedem) [inline rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: The old implementation ignore error like this. Not sure if we should raise error for this. It looks we'd better raise it while some tests are failing because the original tests are too sticky on implementations.

Comment (nzpr) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: I think this error was there before in `checkIndex`? It's just checking of index has been done in the middle two state modifications that are supposed to be one atomic thing. So index check is now performed inside pure computation and error is raised outside.

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala [hunk 2]
```diff
@@ -32,261 +34,388 @@ trait HotStore[F[_], C, P, A, K] {
...
-final case class Cache[C, P, A, K](
-    continuations: TrieMap[Seq[C], Seq[WaitingContinuation[P, K]]] =
-      TrieMap.empty[Seq[C], Seq[WaitingContinuation[P, K]]],
-    installedContinuations: TrieMap[Seq[C], WaitingContinuation[P, K]] =
-      TrieMap.empty[Seq[C], WaitingContinuation[P, K]],
-    data: TrieMap[C, Seq[Datum[A]]] = TrieMap.empty[C, Seq[Datum[A]]],
-    joins: TrieMap[C, Seq[Seq[C]]] = TrieMap.empty[C, Seq[Seq[C]]],
-    installedJoins: TrieMap[C, Seq[Seq[C]]] = TrieMap.empty[C, Seq[Seq[C]]]
+final case class HotStoreState[C, P, A, K](
+    continuations: Map[Seq[C], Seq[WaitingContinuation[P, K]]] =
```
Comment (hilltracer) [inline rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: Can you please say to me: what the difference is Map with TrieMap and which benefit of this change?

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala [hunk 3]
```diff
@@ -32,261 +34,388 @@ trait HotStore[F[_], C, P, A, K] {
...
+private final case class HistoryStoreCache[F[_], C, P, A, K](
+    continuations: Map[Seq[C], Deferred[F, Seq[WaitingContinuation[P, K]]]],
+    datums: Map[C, Deferred[F, Seq[Datum[A]]]],
+    joins: Map[C, Deferred[F, Seq[Seq[C]]]]
+)
+
 private class InMemHotStore[F[_]: Concurrent, C, P, A, K](
-    cacheRef: Ref[F, Cache[C, P, A, K]],
-    historyReader: HistoryReaderBase[F, C, P, A, K]
+    hotStoreState: Ref[F, HotStoreState[C, P, A, K]],
```
Comment (hilltracer) [inline rspace/src/main/scala/coop/rchain/rspace/HotStore.scala:58]: Can you please say to me: what is the point of Ref?

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala (hunk 2 above)
Comment (zsluedem) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: Good question!

Difference:

1. TrieMap is a trie-based **concurrent** scalable map implementation. which is like the `history trie` you are trying to change.It provides an **efficient, non-blocking, O(1) time snapshot operation** while the performance is a little bit slower than `Map` which is just a java `ConcurrentHashMap`.(Getit  from some reading)
2. `TrieMap` is a **mutable** data structure while `Map` here is an **immutable** data structure. Functional programming languages favor immutable data structures which can provide safe concurrent operations.

> which benefit of this change?

There is a bug on hotstore which the data is not consistent after the operation. However, I can not really know the deep detail of the bug which you have to replay thoudsands of time to reproduce it. @nzpr got a pr the change the data into immutable ones and I just rebase the work from him.

@tgrospic @nzpr correct me if I am wrong.

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala (hunk 3 above)
Comment (zsluedem) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala:58]: `Ref` is An asynchronous, concurrent mutable reference. There is an easy example here https://typelevel.org/cats-effect/docs/std/ref.

You can wrap any data structure into a `Ref`and use the operation of `Ref` like `get`, `set` , `getAndUpdate` and etc. to make sure the data structure mutation is totally safe and consistent. The [example](https://typelevel.org/cats-effect/docs/std/ref#concurrent-counter) above is a very good example says how to mutate a data wrapped in a `Ref` in multi threads.

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala (hunk 1 above)
Comment (zsluedem) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: Not sure what you mean here. But I made some changes to include it.

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala (hunk 2 above)
Comment (hilltracer) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: Thanks, for the answers. I have the same structure (TrieMap) for hashing in HistoryStore. And in my code, I don't use the snapshot function. I don't know, what better use in my case. My priority is speed. @tgrospic  @nzpr @zsluedem what do you think?

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala (hunk 3 above)
Comment (hilltracer) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala:58]: Thanks, I try to understand)

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala (hunk 1 above)
Comment (zsluedem) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: I am still in a dilemma to do that.

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala (hunk 2 above)
Comment (zsluedem) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: Oh. In my opinion, You don't have to compare your implementation with scala TrieMap. They are for different use cases. 
1. Your implementation should be able to used either in-memory storage or disk storage while scala TrieMap is only memory. 
2. Your implementation should be able to keep the history track of storage (by stateHash) while scala TrieMap don't do that(But I think you can consider snapshot as somthing similar.)

Comment (nzpr) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: We want to allow HotStore state to change only atomically. TrieMap allows concurrent access which has been used previously. New implementation puts the whole `HotStoreState ` inside a `Ref`, which manages concurrent access. In general, we don't want to have TrieMap-s, because it allows concurrency that is detached from our scheduler and managed by JVM. We want to use `Concurrent` typeclass for our F[_] (which is monix.Task) in places that require concurrency.

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala (hunk 3 above)
Comment (nzpr) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala:58]: Its related to https://github.com/rchain/rchain/pull/3526#discussion_r752948893, you can check https://typelevel.org/cats-effect/docs/std/ref also.

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala [hunk 4]
```diff
@@ -1,16 +1,18 @@
 package coop.rchain.rspace
 
-import cats.effect.Concurrent
-import cats.effect.concurrent.Ref
-import cats.syntax.all._
+import cats._
+import cats.implicits._
```
Comment (tgrospic) [inline rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: Please import `cats.syntax` instead. Do we need `cats._`?

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala (hunk 2 above)
Comment (tgrospic) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: @hilltracer TrieMap cannot be just replaced with Map. Update/insert operation on a Map will return a new _immutable_ instance . TrieMap can be mutated by changing single reference.

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala (hunk 3 above)
Comment (tgrospic) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala:58]: @hilltracer Ref gives the capability to update the value it holds in an atomic way. It's important that this is done without locking, update/modify operations **can** be executed multiple times if concurrently value has changed between the entry and exit of update/modify functions.

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala [hunk 5]
```diff
@@ -32,261 +34,388 @@ trait HotStore[F[_], C, P, A, K] {
...
-        continuations = this.continuations.snapshot(),
-        installedContinuations = this.installedContinuations.snapshot(),
-        data = this.data.snapshot(),
-        joins = this.joins.snapshot(),
-        installedJoins = this.installedJoins.snapshot()
+        continuations = this.continuations,
+        installedContinuations = this.installedContinuations,
+        data = this.data,
+        joins = this.joins,
+        installedJoins = this.installedJoins
```
Comment (tgrospic) [inline rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: This is now immutable object so there is no need to make a copy. Maybe we can even remove Snapshot class as well, if not to invasive change.

Also please create companion object for HotStoreState to construct object with default empty maps.

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala [hunk 6]
```diff
@@ -32,261 +34,388 @@ trait HotStore[F[_], C, P, A, K] {
...
+)
+
 private class InMemHotStore[F[_]: Concurrent, C, P, A, K](
-    cacheRef: Ref[F, Cache[C, P, A, K]],
-    historyReader: HistoryReaderBase[F, C, P, A, K]
+    hotStoreState: Ref[F, HotStoreState[C, P, A, K]],
+    // this is what is inside history store, lazily populated. Starting data for HotStoreState
+    historyStoreCache: Ref[F, HistoryStoreCache[F, C, P, A, K]]
+)(
+    implicit HR: HistoryReaderBase[F, C, P, A, K]
```
Comment (tgrospic) [inline rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: There is not need for history reader to be implicit argument (and be specially named uppercase).

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala [hunk 7]
```diff
@@ -32,261 +34,388 @@ trait HotStore[F[_], C, P, A, K] {
...
+                    joinsInHistoryStore
                   )
-                ignore(
-                  cache.joins.put(
-                    channel,
-                    updated
+                // just return what is in hot store already
+                case Some(joins) =>
+                  (state, joins)
+              })._2
```
Comment (tgrospic) [inline rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: State returned is not used, it's updated at the end of _modify_ function. This is just:
`state.joins.getOrElse(channel, joinsInHistoryStore)`

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala [hunk 8]
```diff
@@ -32,261 +34,388 @@ trait HotStore[F[_], C, P, A, K] {
...
+                    ),
+                    state.installedContinuations.get(join) ++: contsInHistoryStore
                   )
-                )
-                cache
-              } else ().pure[F]
+                // just return what is in hot store already
+                case Some(continuations) =>
+                  (state, state.installedContinuations.get(join) ++: continuations)
+              })._2
```
Comment (tgrospic) [inline rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: State returned is not used, it's updated at the end of _modify_ function.

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala [hunk 9]
```diff
@@ -32,261 +34,388 @@ trait HotStore[F[_], C, P, A, K] {
...
+
+              val index       = curJoins.indexOf(join)
+              val outOfBounds = !curJoins.isDefinedAt(index)
+
+              // TODO should attimpting to remove join with non empty contnuation lead to error as well?
```
Comment (tgrospic) [inline rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: _Remove join_ is called when continuation is removed, so it can be called when continuations are present in which case we just want to skip removal.

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala [hunk 10]
```diff
@@ -29,264 +26,356 @@ trait HotStore[F[_], C, P, A, K] {
...
-                continuations,
-                index
+      fromHistoryStore <- getContFromHistoryStore(channels)
+      r <- hotStoreState.modify[(Boolean, Boolean)](state => {
+            val curVal       = state.continuations.getOrElse(channels, fromHistoryStore)
+            val installedCon = state.installedContinuations.get(channels)
+            val isInstalled  = installedCon.nonEmpty
+
+            val removingInstalled = (isInstalled && index == 0)
+            val removedIndex      = if (isInstalled) index - 1 else index
```
Comment (tgrospic) [inline rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: What is the logic here to use index -1 if _installed_ continuation is trying to be removed?

Also it seems strange to check installed only if index is zero. I don't see when should be allowed to remove installed continuations at all.

@nzpr Is this part of your previous code?

File: rspace/src/test/scala/coop/rchain/rspace/HotStoreSpec.scala [hunk 11]
```diff
@@ -39,35 +41,45 @@ trait HotStoreSpec[F[_], M[_]] extends FlatSpec with Matchers with GeneratorDriv
...
+                                   .arbitrary[
+                                     TrieMap[
+                                       Seq[String],
+                                       WaitingContinuation[Pattern, StringsCaptor]
+                                     ]
+                                   ]
+                                   .map(_.toMap)
+        data           <- Arbitrary.arbitrary[TrieMap[String, Seq[Datum[String]]]].map(_.toMap)
+        joins          <- Arbitrary.arbitrary[TrieMap[String, Seq[Seq[String]]]].map(_.toMap)
+        installedJoins <- Arbitrary.arbitrary[TrieMap[String, Seq[Seq[String]]]].map(_.toMap)
```
Comment (tgrospic) [inline rspace/src/test/scala/coop/rchain/rspace/HotStoreSpec.scala]: `immutable.Map` can be used here instead of TrieMap.

Comment (zsluedem) [reply rspace/src/test/scala/coop/rchain/rspace/HotStoreSpec.scala]: The whole method is not used actually . I just removed it .

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala (hunk 10 above)
Comment (zsluedem) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: > What is the logic here to use index -1 if installed continuation is trying to be removed?

I think this `-1` is added by me. Let me check why is that.

Comment (zsluedem) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: If the channels in Seq[C] contain `installedContinuation`,  the `hotStoreState.getContinuations` would look like `Vector(InstallContinuation ,  normalContinuation)`.

When you remove `continuation` with the `index` provided by `hotStoreState.getContinuations`, the first one is `installed` while `hotStoreState.continuations` doesn't contain the `installedContinuation`. That's why we need to remove 1 in index.

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala [hunk 12]
```diff
@@ -29,264 +26,363 @@ trait HotStore[F[_], C, P, A, K] {
...
+            val isInstalled  = installedCon.nonEmpty
+
+            val removingInstalled = (isInstalled && index == 0)
+            // why -1 here
+            // from users who use `HotStore` trait perspective
+            // the users need to call getContinuations first to retrieve the continuation of the channels
+            // then find which index of the continuation users want to remove
+            // while getContinuations would return results like `Vector(installedContinuation, normalcontinuations, ...)`
+            // The first one would be always `installedContinuation` if it exist which need the
+            // index to -1 to exclude installedContinuation
```
Comment (nzpr) [inline rspace/src/main/scala/coop/rchain/rspace/HotStore.scala:118]: But index supplied here already accounts the presence of installed continuations. When you match produce over Seq of continuations, you will see the installed one, as you aways get it through `getContinuations`. I don't think you can modify index here.

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala (hunk 10 above)
Comment (nzpr) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: Yes, this is a change compared to my code and old implementation as well.
In previous code index to remove is supplied as input arg is unchanged in the method.

```scala
def removeContinuation(channels: Seq[C], index: Int): F[Unit] =
    for {
      continuations <- getContinuations(channels)
      cache         <- cacheRef.get
      installed     = cache.installedContinuations.get(channels)
      _ <- if (installed.isDefined && index == 0) {
            new IllegalArgumentException("Attempted to remove an installed continuation").raiseError
          } else
            checkIndex(continuations, index) >> cacheRef.update { cache =>
              val updated = removeIndex(
                continuations,
                index
              )
              ignore(installed match {
                case Some(_) => cache.continuations.put(channels, updated tail)
                case None    => cache.continuations.put(channels, updated)
              })
              cache
            }
    } yield ()
```
@zsluedem I think your change masks the situation when previously error has been thrown. Now it just does nothing, as removing of index -1 does nothing. I've added one more comment https://github.com/rchain/rchain/pull/3526#discussion_r760451380

Comment (zsluedem) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: @nzpr In previous code，
```scala
              val updated = removeIndex(
                continuations,
                index
              )
```

The `continuations` above include `installedContinuation` and `normalContinuation` while in the new codes without my fix(index - 1) below.

```scala
  def removeContinuation(channels: Seq[C], index: Int): F[Unit] =
    for {
      fromHistoryStore <- getContFromHistoryStore(channels)
      r <- hotStoreState.modify[(Boolean, Boolean)](state => {
            val curVal      = state.continuations.getOrElse(channels, fromHistoryStore)
            val isInstalled = state.installedContinuations.contains(channels)

            val removingInstalled = (isInstalled && index == 0)
            val outOfBounds       = !curVal.isDefinedAt(index)

            if (removingInstalled || outOfBounds)
              (state, (removingInstalled, outOfBounds))
            else {
              val newVal = removeIndex(curVal, index)
              // TODO Logic behind this isInstalled check is uncertain
              if (isInstalled)
                (
                  state.copy(continuations = state.continuations.updated(channels, newVal.tail)),
                  (false, false)
                )
              else
                (
                  state.copy(continuations = state.continuations.updated(channels, newVal)),
                  (false, false)
                )
            }

          })
      (removingInstalled, invalidIndex) = r
      _ <- Sync[F]
            .raiseError {
              new IllegalArgumentException("Attempted to remove an installed continuation")
            }
            .whenA(removingInstalled)
      _ <- Sync[F]
            .raiseError(
              new IndexOutOfBoundsException(
                s"Index ${index} out of bounds when removing continuation"
              )
            )
            .whenA(invalidIndex)
    } yield ()
```

the `val newVal = removeIndex(curVal, index)` which `curVal` is just `continuations` without `installedContinuations`.

Comment (nzpr) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala]: I see, thanks, so old hotstore has installedContinuations in `curVal` and my code does not. Ok, thanks!

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala [hunk 13]
```diff
@@ -29,264 +26,363 @@ trait HotStore[F[_], C, P, A, K] {
...
-                    updated
-                  )
-                )
-                cache
-              } else ().pure[F]
+      joinsInHistoryStore <- getJoinsFromHistoryStore(channel)
+      contsInHistoryStore <- getContFromHistoryStore(join)
+      err <- hotStoreState.modify[Boolean](state => {
+
+              val curJoins = state.joins.getOrElse(channel, joinsInHistoryStore)
```
Comment (nzpr) [inline rspace/src/main/scala/coop/rchain/rspace/HotStore.scala:261]: @zsluedem I'm thinking - is here with joins situation the same as with continuations? `curJoin` here does not account installed.

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala (hunk 12 above)
Comment (tgrospic) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala:118]: Previously continuations are retrieved with `getContinuations` which included installed, but now they are accessed directly from the state without installed.

I'm OK with this solution for now (it's works the same as previous) until we came up with more elegant one.

Comment (nzpr) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala:118]: Yes I agree https://github.com/rchain/rchain/pull/3526#discussion_r761162294

File: rspace/src/main/scala/coop/rchain/rspace/HotStore.scala (hunk 13 above)
Comment (zsluedem) [reply rspace/src/main/scala/coop/rchain/rspace/HotStore.scala:261]: `removeJoin` got very specific target on removing

```
def removeJoin(channel: C, join: Seq[C])`
```

Not like continuations want `index`

**Review by tgrospic — APPROVED** [review]
LGTM

**Review by nzpr — APPROVED** [review]
LGTM

**Comment by tgrospic** [comment]
bors merge
