### PR TITLE
Require latest messages justifications for LFS

### LINKED ISSUE #3483: Starting node on new hf1 network with lfs would get inconsistent dag error
docker run command
```
        "run",
        "--bootstrap=rnode://ef34d5e196c8292cfe0da69d7df2e9ae6cea0be2@node0.root-shard.mainnet.rchain.coop?protocol=40400&discovery=40404",
        "--network-id=mainnet1",
        "--shard-name=root1",
        "--fault-tolerance-threshold=-1",
        "--api-enable-reporting",
        "--finalization-rate=1",
        "--max-number-of-parents=1"
```

After the node finish downloading the state and the approved block, the  node would raise error like below
```
rnode    | 05:26:01.590 [INFO ] [node-runner-28      ] [c.r.c.engine.Initializing    ] - Approved state for block #908739 (f618d141a5...) is successfully restored.
rnode    | 05:26:02.239 [INFO ] [node-runner-29      ] [c.r.c.MultiParentCasperImpl  ] - Validating block #908740 (d55b77c98f...).
rnode    | 05:26:02.654 [ERROR] [node-runner-28      ] [c.r.node.runtime.NodeRuntime ] - Caught unhandable error. Exiting. Stacktrace below.
rnode    | coop.rchain.blockstorage.dag.BlockDagInconsistencyError: DAG storage is missing hash b9df500556...
rnode    |      at coop.rchain.blockstorage.dag.BlockDagRepresentationOps$.$anonfun$lookupUnsafe$extension0$1(BlockDagRepresentationSyntax.scala:41)
rnode    |      at cats.ApplicativeError$LiftFromOptionPartially$.apply$extension(ApplicativeError.scala:305)
rnode    |      at cats.syntax.OptionOps$LiftToPartiallyApplied.apply(option.scala:374)
rnode    |      at coop.rchain.blockstorage.dag.BlockDagRepresentationOps$.$anonfun$lookupUnsafe$1(BlockDagRepresentationSyntax.scala:41)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |
rnode exited with code 0
```

### PR DESCRIPTION
**Pull request by nzpr**
## Overview
Current version of LFS does not pull enough blocks that are required for validation. 
This PR makes sure all latest messages self justifications are pulled as part of LFS state.
Closing https://github.com/rchain/rchain/issues/3483

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

File: casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala [hunk 1]
```diff
@@ -82,7 +87,8 @@ object LfsBlockRequester {
         // Calculate new minimum height if latest message
         //  - we need parents of latest message so it's `-1`
         val newLowerBound = if (isLatest) Math.min(height - 1, lowerBound) else lowerBound
-        val newSt         = d + ((k, Received))
+        val newSt =
+          latestReplacement.foldLeft(d + ((k, Received)))((acc, k) => acc + (k -> Requested))
```
Comment (tgrospic) [inline casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala]: 1. ~~Why is here `latestReplacement` added as received?~~ It's Requested!
2. Where is `latestReplacement` block height captured for min height calculation?

File: casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala [hunk 2]
```diff
@@ -192,7 +198,16 @@ object LfsBlockRequester {
...
-          receivedResult <- st.modify(_.received(block.blockHash, blockNumber))
+          receivedResult <- st.modify(st => {
+                             val isAbLatest = latestMessages.contains(block.blockHash)
+                             if (isAbLatest) {
+                               val selfJustification =
+                                 ProtoUtil.creatorJustification(block).map(_.latestBlockHash)
+                               // if message received is latest as per approved block - add its self justification
+                               // to target latest messages that has to be pulled
+                               st.received(block.blockHash, blockNumber, selfJustification)
+                             } else st.received(block.blockHash, blockNumber, None)
```
Comment (tgrospic) [inline casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala]: These lines are duplicated in first two arguments. If block should only be for third argument.

**Review by zsluedem — APPROVED** [review]
LGTM

File: casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala (hunk 1 above)
Comment (nzpr) [reply casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala]: here lower bound overwritten https://github.com/rchain/rchain/blob/cafbda84eafb97153292f063fe3b7114adc0e3f0/casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala#L84
>>
and here block is rejected if it is lower, right?
https://github.com/rchain/rchain/blob/cafbda84eafb97153292f063fe3b7114adc0e3f0/casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala#L208-L223

Comment (tgrospic) [reply casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala]: Oh, I see. It will be calculated in the same way when this _latest replacement_ is received.

Maybe we can simplify this even more. If replacement message is added to `latest` on the begging, rest of the function can stay unchanged.

```scala
if (isReq) {
  // Replace latest message with replacement if supplied
  val latestWithR = latestReplacement.map(latest - k + _).getOrElse(latest)
  // Remove message from the set of latest messages (if exists)
  val newLatest    = latestWithR - k
  val isLatest     = latest != newLatest
```
In that way we don't need to take care of Request created for new latest replacement and leave existing mechanism to work the same. Old latest will not even be detected as latest because it's replaced by new latest.

File: casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala [hunk 3]
```diff
@@ -223,8 +223,26 @@ class Initializing[F[_]
...
+                                     .get
+                                 BlockStore[F]
+                                   .get(selfJ)
+                                   .flatMap(_.liftTo(new Exception(noSelfJustificationErr)))
+                                   .map(_.body.state.blockNumber)
+                               }
+                               .compile
+                               .toList
+
+        minHeight = if (lowestBlockHeights.isEmpty) 0L else lowestBlockHeights.min
```
Comment (tgrospic) [inline casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala]: I made this to complicated, this calculation of min height here is not really necessary, which I totally missed.

Here we have final result of requester with min height calculated in `lowerBound`.
https://github.com/rchain/rchain/blob/c06fb989d16568f578863d8e343013f5e704e420/casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala#L194-L197

So instead we can re-use it and not have same logic in two places.
```scala
// Receive the blocks and after populate the DAG
blockRequestAddDagStream = blockRequestStream.last.unNoneTerminate.evalMap { st =>
  populateDag(approvedBlock.candidate.block, st.lowerBound, st.heightMap)
}
```

File: casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala (hunk 1 above)
Comment (tgrospic) [reply casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala]: I pushed this change and removed unnecessary calculation in initializing engine.

**Review by tgrospic — APPROVED** [review]

**Comment by nzpr** [comment]
bors merge

**Comment by tgrospic** [comment]
bors merge
