### PR TITLE
Temp fix. Add constraints on traversing DAG when calculating LCA

### LINKED ISSUE #3094: Fork-choice tip calculation grows linearly
After epoch change we have latest message from non active validators participating in calculation of FCT. This leads to increasing of FCT calculation time, because DAG height on which this calculation is being performed grows as network proceeds.

This code slows down 
https://github.com/rchain/rchain/blob/27787e1f47392e1998135db2316c2c32651abf4d/casper/src/main/scala/coop/rchain/casper/Estimator.scala#L51-L72
Screenshot 2020-08-22 at 13 55 27

On testnet this code takes milliseconds.

### PR DESCRIPTION
**Pull request by nzpr**
This is a replacement for <https://github.com/rchain/rchain/pull/3095>. It does not touch justifications. It changes ~~how LCA is calculated and latest messages are ranked, but only for very old blocks (~1000 blocks behind top of the DAG).~~. I t turned out that its enough to just not use very old blocks for LCA calculation. It makes ranking fast as well, because of specifics of ranker implementation.

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

File: casper/src/main/scala/coop/rchain/casper/Estimator.scala [hunk 1]
```diff
@@ -151,13 +151,31 @@ final class Estimator[F[_]: Sync: Log: Metrics: Span](
...
+    }*/
+
+    // Initial code above that commented out is slow when there is old latest message.
+    // The below solution is a temp solution until we have efficient way to calculate LCA.
+    latestMessagesHashes.toList.foldLeftM(Map.empty[BlockHash, Long]) {
+      case (acc, (validator: Validator, latestBlockHash: BlockHash)) =>
+        for {
+          topBlockNumber           <- blockDag.latestBlockNumber
+          latestMessageBlockNumber <- blockDag.lookup(latestBlockHash).map(_.get.blockNum)
+          r <- if (topBlockNumber - latestMessageBlockNumber > 1000)
```
Comment (zsluedem) [inline casper/src/main/scala/coop/rchain/casper/Estimator.scala]: I like this fix better than the before one~! Good work. 
However, I am still picky on this hard-coded `1000`. :)
I saw this `1000` is used in multiple place. We'd better define a `val` currently and use that value in one place for now.

File: casper/src/main/scala/coop/rchain/casper/util/DagOperations.scala [hunk 2]
```diff
@@ -109,7 +110,12 @@ object DagOperations {
 
     if (b1 == b2) {
       b1.pure[F]
-    } else {
+    } else
+    // This constraints are a temp solution, we need to make LCA calculation fast. For now it is assumed
+    // that when one block is `staleLatestMessageThreshold` behind another - it is LCA for this pair.
+    if (b1.blockNum - b2.blockNum > Estimator.depth) b2.pure[F]
+    else if (b2.blockNum - b1.blockNum > Estimator.depth) b1.pure[F]
```
Comment (tgrospic) [inline casper/src/main/scala/coop/rchain/casper/util/DagOperations.scala]: So this is just an optimization. It will not change the result because this very old block will be anyway returned as LCA. Is that right?

Comment (nzpr) [reply casper/src/main/scala/coop/rchain/casper/util/DagOperations.scala]: @tgrospic yes, but in general case you never know what should be `Estimator.depth`. If we have some slashing conditions like `you have to propose at least each N blocks`, this condition can be justified.

Comment (nzpr) [reply casper/src/main/scala/coop/rchain/casper/util/DagOperations.scala]: But even then you cannot be sure how temporary forking influence this. Looks like you don't have much options except traversing the DAG till you find one LCA. Thats why I'm thinking - might be we can keep a records for joint LCAs for different blocks and somehow incrementally update. But thats just a raw guess.

Comment (9rb) [reply casper/src/main/scala/coop/rchain/casper/util/DagOperations.scala]: https://uhra.herts.ac.uk/bitstream/handle/2299/12152/906535.pdf
https://java2blog.com/lca-k-ary-tree-osqrtheight/

**Comment by nzpr** [comment]
I changed the hotfix logic. Taking into account how the Estimator code is written - this is enough. We only ned to filter very old messages when calculating LCA. Why it works for other parts of the code - is not very clear from the first glance and hidden by the actual implementation. So anyway, we need to rewrite estimator at some point (I think when doing block merge).

File: casper/src/main/scala/coop/rchain/casper/Estimator.scala [hunk 3]
```diff
@@ -99,16 +99,20 @@ final class Estimator[F[_]: Sync: Log: Metrics: Span](
...
+      )
+      result <- if (filteredLM.isEmpty) {
                  genesis.blockHash.pure[F]
                } else {
-                 latestMessages
-                   .foldM(latestMessages.head) {
-                     case (acc, latestMessage) =>
+                 filteredLM
+                   .foldM(filteredLM.head) {
+                     case (acc, filteredLM) =>
```
Comment (tgrospic) [inline casper/src/main/scala/coop/rchain/casper/Estimator.scala]: Now one item has the same name as the collection. Existing name seems reasonable.

Comment (nzpr) [reply casper/src/main/scala/coop/rchain/casper/Estimator.scala]: Thanks, indeed

**Review by tgrospic — APPROVED** [review]
I'm OK with this optimization until we have block merging.

**Review by zsluedem — APPROVED** [review]
LGTM

**Comment by nzpr** [comment]
bors merge
