### PR TITLE
Transport layer in-memory cache

### LINKED ISSUE #3098: Testing of LFS
## Overview

This issue is to record several rounds of testing of **Last Finalized State** pre release versions. Tests are more performance oriented and some of the bug fixes and optimitations are done between each test setup.

Results are starting from the last setup. Shows how speed is increased with stronger machine. This is due to additonal computation needed for verification of the Rholang state (#3145). This is visible in high usage of CPU during sync.  

Another important factor is disk speed. All tests are done on SSD disks and on stronger machines faster speed reduces overall sync duration.

### Testing setup 4

This round is almost identical to _setup 3_ with additional optimization in receiving blocks (#3243) which include block sorting as part of download and with testing on 32 vCPU machine.

RNode Docker image version: [`rchain/rnode:v0.9.26-rc`](https://hub.docker.com/layers/rchain/rnode/v0.9.26-rc/images/sha256-af9d5c6467474eb6e47d1557dfdef26c312a5834eeb3fed5c94b8d6ce25a5ee9?context=explore)

| Nr. | Sync time<br>(fully catch up) | Sync Rholang state | Sync blocks | VPS | Log
| --- | ---        | ---    | ---    | ---                         | ---
| 1   | **2.25 h** | 1.5 h  | 1.75 h | 32vCPU 64GB (DigitalOcean)  | [test-4-do-32vcpu-64g.zip](https://github.com/rchain/rchain/files/5630012/test-4-do-32vcpu-64g.zip)
| 2   | **3.25 h** | 1.5 h  | 2 h    | 16vCPU 32GB CPX51 (Hetzner) | [test-4-cpx51-32g.zip](https://github.com/rchain/rchain/files/5630016/test-4-cpx51-32g.zip)
| 3   | **3 h**    | 1.75 h | 2 h    | 8vCPU 32GB (IBM)                   | [test-4-ibm-8vcpu-32g.zip](https://github.com/rchain/rchain/files/5630025/test-4-ibm-8vcpu-32g.zip)
| 4   | **4 h**    | 2.25 h | 2.5 h  | 8vCPU 16GB CPX41 (Hetzner)  | [test-4-cpx41-16g.zip](https://github.com/rchain/rchain/files/5630022/test-4-cpx41-16g.zip)
| 5   | **8 h**    | 4.5 h  | 3.5 h  | 4vCPU 8GB CPX31 (Hetzner)   | [test-4-cpx31-8g.zip](https://github.com/rchain/rchain/files/5630030/test-4-cpx31-8g.zip)

NOTE: CPU and memory observed in testing is the same as in setup 3, only overall duration is shorter.

[1] CPU, memory - 32vCPU 64GB (DigitalOcean)
test-4-do-32vcpu-64g-lfs-progress-cpu

### Testing setup 3

First two rounds of testing showed that LFS source node disk reading speed can make significant difference in overall speed for nodes to download Rholang state. In this testing setup,  to make reading from disk much faster RSpace folder on source node is converted to RAM disk which reduced reading from ~20sec to ~1sec for chunk of state sent over the network.

RNode Docker image version: [`tgrospic/rnode:v0.9.26-rc`](https://hub.docker.com/layers/tgrospic/rnode/v0.9.26-rc/images/sha256-85bb8d444b354b0628d871b561c2e908131f79cef880ece5b86678f64fb49195?context=repo)

NOTE: Bug with memory leak on network errors is still not resolved and one test with 8GB machine failed not listed in results.

| Nr. | Sync time<br>(fully catch up) | VPS
| --- | ---  | --- | 
| 1 | 4 hours (2.5 h blocks)<br>[test-3-cpx51-32g-full-ok-3.zip](https://github.com/rchain/rchain/files/5629935/test-3-cpx51-32g-full-ok-3.zip) | 16vCPU 32GB CPX51
| 2 | 5.5 hours (3.5 h blocks)<br>[test-3-cpx41-16g-full-ok-1.zip](https://github.com/rchain/rchain/files/5629947/test-3-cpx41-16g-full-ok-1.zip) | 8vCPU 16GB CPX41
| 3 | 9 hours (4.5 h blocks)<br>[test-3-cpx31-8g-full-ok-1.zip](https://github.com/rchain/rchain/files/5629957/test-3-cpx31-8g-full-ok-1.zip) | 4vCPU 8GB CPX31

#### Observations from testing

[1] CPU, memory - 16vCPU 32GB CPX51
test-3-cpx51-32g-lfs-progress-cpu

[1] Direct buffer - 16vCPU 32GB CPX51
test-3-cpx51-32g-lfs-progress-buffer

[2] CPU, memory - 8vCPU 16GB CPX41
test-3-16g-lfs-progress-cpu

[3] CPU, memory - 4vCPU 8GB CPX31
test-3-8g-lfs-progress-cpu

Survived network errors without crashing - 4vCPU 8GB CPX31
test-3-8g-lfs-progress-3-errors-cpu

### Testing setup 2

RNode Docker image version: [`tgrospic/rnode:v0.9.26-beta`](https://hub.docker.com/layers/tgrospic/rnode/v0.9.26-beta/images/sha256-0734a74f064939d43208d82c6914f64a0917b4de95cca0ae863a3999f2d53e3c?context=repo)

| Nr. | Source | Duration | Sync time<br>(fully catch up) | Environment
| --- | ---  | ---   | --- | ---
| 1 | Full  | 12.5 hours (2.5 h blocks) | - | One machine + 3 active nodes
| 2 | LFS  | ERROR interrupted<br>[rnode-restart-error.zip](https://github.com/rchain/rchain/files/5241197/rnode-restart-error.zip) | - | Target alone on another machine<br>(Docker on Hetzner cloud CPX31)
| 3 | LFS [2] | 4.5 hours (2.5 blocks)<br> [rnode-test-3.zip](https://github.com/rchain/rchain/files/5244082/rnode-test-3.zip) | 8 hours | Target alone on another machine<br>(Docker on Hetzner cloud CPX31)
| 4 | LFS [3] | 6 hours (2 blocks)<br> [rnode-test-4.zip](https://github.com/rchain/rchain/files/5248452/rnode-test-4.zip) | 10 hours | Target alone on another machine<br>(Docker on Hetzner cloud CX31)

#### Observations from testing

[3] After node received LFS, it's not responding to requests for tuple space (_StateItems_). After restart it works as expected.

[2] CPU, memory
image

[2] Direct buffer memory
image

### Testing setup 1

~Trie traversal is slow when number of records is bigger then 3,000 and it's rising faster then linear.~ Resolved in PR #3099.

Performance of LFS should be tested with this configuration.

RNode Docker image for all nodes: [`rchain/rnode:v0.9.26-alpha`](https://hub.docker.com/layers/rchain/rnode/v0.9.26-alpha/images/sha256-8dee109eb6bb377a8912111e09489ea105f926eb36d3d6a53e5195738d170d60?context=explore)

1. Observer node with full state
2. Observer node with empty state (bootstrap from `1.`)
3. Observer node with empty state (bootstrap from `2.`)

~Observer nodes with empty state (2. and 3.) must have higher limit for direct buffer memory to 3GB.
`-XX:MaxDirectMemorySize=3g`~
Memory leak with direct buffer is fixed in transport layer #3239 so now limit can be much lower.
`-XX:MaxDirectMemorySize=200m`

First operation is to test syncing of LFS from the full node. When this is done second syncing should use this node with _trimmed_ state as a source to sync the third node.

| Operation | Expected    | Measured
| ---       | ---         | ---
| 1. -> 2.  | 4-6 hours   | 7.5 hours (one machine + 1 active nodes)<br>11 hours (one machine + 4 active nodes)
| 2. -> 3.  | 1-3 hours   | 4 hours (one machine + 4 active nodes)

### LINKED ISSUE #3173: Transport layer cache redesign
## Overview
Streaming packets in transport layer is currently implemented with file based cache. For each blob of data one file is created and chunks are appended as they are received.
Last Finalized State requires large amount of data (blocks and Rholang state) to be transferred which exposed some problems in memory consumption. Is seems some kind of memory leak with the use of direct buffer memory, it's constantly increasing until usually 2-2.5 GB when LFS process is finished.
This causing kernel to kill the node even use of heap (or direct buffer memory) is not even close to the limit.

## Solution
Proof of concept solution to store chunks in memory has shown improvements and direct buffer memory is stable. Overall memory usage (reported by `systemd-cgtop`) is still much higher than heap but about 30% lower that with file cache.
My assumption is that this is related to network buffering in `scalapb`-connected libraries like grpc-netty, protobuf, netty. Upgrade of these is still not possible #3170.

## Testing results
Graphs shows about first 10 minutes when LFS node is downloading blocks (CPU ~50%), this is without state chunks. After few minutes state chunks are also starting to receive which is visible on CPU usage (~70%).
Direct buffer memory shows how with file cache it's increasing even when GC is run, visible in drops in heap memory.

**Machine and node setting**: 16GB / JVM heap max 75% / Direct buffer max 500MB

#### File cache: direct buffer memory
2020-10-14-cx41-lfs-transport-file-cache-buffer-2

#### In-memory cache: direct buffer memory
2020-10-14-cx41-lfs-transport-mem-cache-buffer

#### File cache: CPU and heap
2020-10-14-cx41-lfs-transport-file-cache-cpu-2

#### In-memory cache: CPU and heap
2020-10-14-cx41-lfs-transport-mem-cache-cpu

### PR DESCRIPTION
**Pull request by tgrospic**
## Overview
This PR fixes slow memory leak with direct buffer when transport layer receives stream of messages. The problem is described in the linked issue.

Another problem found in LFS testing is slowdown in processing of inbound queue. The fix is in gRPC receiver, fixed scheduler is replaced with main scheduler. 

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

File: node/src/main/scala/coop/rchain/node/Main.scala [hunk 1]
```diff
@@ -45,7 +45,7 @@ object Main {
     // Should always be passed as implicit dependency.
     // All other schedulers should be explicit.
     implicit val scheduler: Scheduler = Scheduler.computation(
-      Math.max(java.lang.Runtime.getRuntime.availableProcessors(), 2),
+      Math.max(java.lang.Runtime.getRuntime.availableProcessors() * 4, 2),
```
Comment (tgrospic) [inline node/src/main/scala/coop/rchain/node/Main.scala:48]: The reason to increase parallel tasks is because of sync blocking calls to LMDB. This is noticeable when downloading LFS with large number of blocks together with state validation which is CPU intensive. More parallelism enables more CPU to be utilized even if some tasks are blocked synchronously.

File: comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportReceiver.scala [hunk 2]
```diff
@@ -167,10 +161,10 @@ object GrpcTransportReceiver {
 
     val server = NettyServerBuilder
       .forPort(port)
-      .executor(scheduler)
+      .executor(mainScheduler)
```
Comment (tgrospic) [inline comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportReceiver.scala:163]: With this scheduler the whole netty/grpc stack is executed so it is not exclusively _io_ bound and it's more part of the same computation with our code on main scheduler.

File: comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportReceiver.scala [hunk 3]
```diff
@@ -64,10 +57,10 @@ object GrpcTransportReceiver {
           // TODO cancel queues when peer is lost
```
Comment (tgrospic) [inline comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportReceiver.scala:57]: Buffers were on _io_ scheduler which also doesn't make sense because the are not doing any _io_.

File: casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala [hunk 4]
```diff
@@ -165,7 +165,7 @@ class TestNode[F[_]](
       Created(block)    = createBlockResult
     } yield block
 
-  def receive(): F[Unit] = tls.receive(p => handle[F](p), kp(().pure[F])).void
+  def receive(): F[Unit] = tls.handleReceive(p => handle[F](p), kp(().pure[F])).void
```
Comment (nzpr) [inline casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala:168]: I'm not sure about this change. As I understand it - this actually triggers acquiring of messages

**Review by nzpr — APPROVED** [review]
LGTM

File: casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala (hunk 4 above)
Comment (tgrospic) [reply casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala:168]: The `handleReceive` is not actually the function that is doing processing, it's a function that receives a function which will do the processing.

File: comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportReceiver.scala [hunk 5]
```diff
@@ -144,7 +137,7 @@ object GrpcTransportReceiver {
                   else
                     Metrics[F].incrementCounter("stream.chunks.dropped") >>
                       Log[F].debug(msgDropped) >>
-                      msg.path.deleteSingleFile[F] >>
+                      Sync[F].delay(cache.remove(msg.key)) >>
```
Comment (zsluedem) [inline comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportReceiver.scala:140]: I just wanted to say that I think the old team used file cache instead of memory cache is because rchain used to take storing-big-files as a sell point(which I think dappy wanted to do at very first) and using file cache can make the node not to blow up easily.

Comment (tgrospic) [reply comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportReceiver.scala:140]: I agree, but this kind of optimization should not be part of transport layer. The idea is to refactor it in way that we can add e.g. LMDB cache if needed for large files. This PR is intermediate solution fix the leak and to enable transition to better solution.

Comment (zsluedem) [reply comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportReceiver.scala:140]: I agree with you. Just want to mention that.

**Review by zsluedem — APPROVED** [review]
LGTM

**Comment by tgrospic** [comment]
bors merge

**Comment by tgrospic** [comment]
bors merge
