### PR TITLE
Fix and re-enable block retriever spec

### LINKED ISSUE #3313: BlockRetriever tests not executed on CI
### What did you expect to see?
All test in Casper project executed on CI.

### What did you see instead?
Tests of BlockRetriever are not executed as part of CI.

Some tests are failing when run locally:
[BlockRetrieverSpec.scala](https://github.com/rchain/rchain/blob/a52667ad86497ef97593b0dddf2d89a4814b4801/casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverSpec.scala)
image

[BlockRetrieverRequesAllSpec.scala](https://github.com/rchain/rchain/blob/a52667ad86497ef97593b0dddf2d89a4814b4801/casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala)
image

### Solution
Add `sync` folder also to CI excution.
https://github.com/rchain/rchain/blob/23ae5cec355baec472e204106fde8e9a779c64a1/.github/workflows/continuous-integration.yml#L88-L96

### PR DESCRIPTION
**Pull request by nzpr**
## Overview
Closes https://github.com/rchain/rchain/issues/3313

Some logical flaws has been fixed. For details see comments.

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

File: casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverSpec.scala [hunk 1]
```diff
@@ -49,7 +49,7 @@ class BlockRetrieverSpec extends FunSpec with BeforeAndAfterEach with Matchers {
   override def beforeEach(): Unit = {
     transportLayer.reset()
     transportLayer.setResponses(_ => p => Right(()))
-    currentRequests.update(Map.empty)
+    currentRequests.set(Map.empty).runSyncUnsafe()
```
Comment (nzpr) [inline casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverSpec.scala:52]: It is required for requests map to be cleared after each test.

File: casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverSpec.scala [hunk 2]
```diff
@@ -92,6 +92,9 @@ class BlockRetrieverSpec extends FunSpec with BeforeAndAfterEach with Matchers {
 
       describe("when source peer is unknown") {
         it("should ignore hash") {
+          blockRetriever
+            .admitHash(hash, peer = None, admitHashReason = testReason)
+            .runSyncUnsafe()
```
Comment (nzpr) [inline casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverSpec.scala:97]: This tests assumed that there is already record in requests map, so admitting of a hash with no peer associated should not produce a request. As now requests map is cleared before test, it should be populated here.

File: casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala [hunk 3]
```diff
@@ -31,7 +31,7 @@ import monix.execution.Scheduler.Implicits.global
 
 import scala.concurrent.duration._
 
-class BlockRetrieverRequesAllSpec extends FunSpec with BeforeAndAfterEach with Matchers {
+class BlockRetrieverRequestAllSpec extends FunSpec with BeforeAndAfterEach with Matchers {
```
Comment (nzpr) [inline casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala:34]: This test have some logical flaw. E.g. if only one peer is left in waiting list, block has to be requested from this peer, but test expects that block is not requested and broadcast of HasBlockRequest happening instead.

File: casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverSpec.scala (hunk 2 above)
Comment (zsluedem) [reply casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverSpec.scala:97]:
```
      describe("when source peer is unknown") {
        it("should ignore hash") {
```

The description above is not describing what you are trying to test. Could you please change the descriptions?

Just curious. In your description above, what is the role of `peer=None`play here?

File: casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala [hunk 4]
```diff
@@ -189,10 +175,29 @@ class BlockRetrieverRequesAllSpec extends FunSpec with BeforeAndAfterEach with M
...
           }
         }
+        it(
+          "should remove the entry from the requested block lists when block is in casper buffer and after timeout"
+        ) {
+          // given
+          val waitingList = List.empty[PeerNode]
+          val requested = RequestState(
+            timestamp = timedOut,
+            inCasperBuffer = true,
```
Comment (zsluedem) [inline casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala:169]: Just curious. Why the `inCasperBuffer=true` is added

File: casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverSpec.scala (hunk 2 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverSpec.scala:97]: The description is
```
describe("when hash is known") {
    describe("when source peer is unknown") {
        it("should ignore hash") {
```

This  `peer = None` is used when dependency is requested. 
When hash broadcast hit the node there is an information about peer which is saying that the hash is something of interest. So this peer can be immediately added to source (waiting) list, and peer is defined.

In the case of dependency request - there is nothing to add to waiting list, but BlockRequester should be notified to retrieve dependency hash. In this case `peer = None` and node has to broadcast HasBlockRequest.

File: casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala (hunk 4 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala:169]: It is not required and wont influence test case, looks like leftover from other case.  I removed it.

File: casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala [hunk 5]
```diff
@@ -141,7 +142,7 @@ class BlockRetrieverRequesAllSpec extends FunSpec with BeforeAndAfterEach with M
           }
         }
         describe("if waiting list has one peer left") {
-          it("should broadcast HasBlockRequest") {
+          it("should ask that peer") {
```
Comment (tgrospic) [inline casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala]: This test seems duplicated of _should request block from first peer on a waiting list_.

File: casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala (hunk 3 above)
Comment (tgrospic) [reply casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala:34]: What are you suggesting as a solution?

**Comment by tgrospic** [comment]
BlockRetriever is spamming the log with these messages.
```
10:53:48.926 [DEBUG] [node-runner-35      ] [c.r.c.MultiParentCasperImpl  ] - Requesting CasperBuffer pendant hashes, 0 items.
10:53:48.926 [DEBUG] [node-runner-35      ] [.r.c.e.BlockRetriever$$anon$1] - Running BlockRetriever maintenance (1 items unexpired).
10:54:18.927 [DEBUG] [node-runner-62      ] [c.r.c.MultiParentCasperImpl  ] - Requesting CasperBuffer pendant hashes, 0 items.
10:54:18.927 [DEBUG] [node-runner-62      ] [.r.c.e.BlockRetriever$$anon$1] - Running BlockRetriever maintenance (0 items unexpired).
10:54:48.928 [DEBUG] [node-runner-55      ] [c.r.c.MultiParentCasperImpl  ] - Requesting CasperBuffer pendant hashes, 0 items.
10:54:48.928 [DEBUG] [node-runner-55      ] [.r.c.e.BlockRetriever$$anon$1] - Running BlockRetriever maintenance (0 items unexpired).
10:55:18.929 [DEBUG] [node-runner-55      ] [c.r.c.MultiParentCasperImpl  ] - Requesting CasperBuffer pendant hashes, 0 items.
10:55:18.929 [DEBUG] [node-runner-55      ] [.r.c.e.BlockRetriever$$anon$1] - Running BlockRetriever maintenance (0 items unexpired).
```
But the main issue is that this happens in LFS process also. Please check why BlockRetriever is active even when LFS process is not done.

File: casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala (hunk 3 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala:34]: The changes are the solution. I meant that changes in this test are justified by the fact that previously test had logical flaws that are fixed. As per this test broadcast had been done when requesting block from last peer in waiting list. It does not make sense because this peer might answer. It makes sense to do broadcast only when no waiting peers are left, because on response to the broadcast node will immediately ask for the full block.

**Comment by nzpr** [comment]
> BlockRetriever is spamming the log with these messages.
> 
> ```
> 10:53:48.926 [DEBUG] [node-runner-35      ] [c.r.c.MultiParentCasperImpl  ] - Requesting CasperBuffer pendant hashes, 0 items.
> 10:53:48.926 [DEBUG] [node-runner-35      ] [.r.c.e.BlockRetriever$$anon$1] - Running BlockRetriever maintenance (1 items unexpired).
> 10:54:18.927 [DEBUG] [node-runner-62      ] [c.r.c.MultiParentCasperImpl  ] - Requesting CasperBuffer pendant hashes, 0 items.
> 10:54:18.927 [DEBUG] [node-runner-62      ] [.r.c.e.BlockRetriever$$anon$1] - Running BlockRetriever maintenance (0 items unexpired).
> 10:54:48.928 [DEBUG] [node-runner-55      ] [c.r.c.MultiParentCasperImpl  ] - Requesting CasperBuffer pendant hashes, 0 items.
> 10:54:48.928 [DEBUG] [node-runner-55      ] [.r.c.e.BlockRetriever$$anon$1] - Running BlockRetriever maintenance (0 items unexpired).
> 10:55:18.929 [DEBUG] [node-runner-55      ] [c.r.c.MultiParentCasperImpl  ] - Requesting CasperBuffer pendant hashes, 0 items.
> 10:55:18.929 [DEBUG] [node-runner-55      ] [.r.c.e.BlockRetriever$$anon$1] - Running BlockRetriever maintenance (0 items unexpired).
> ```
> 
> But the main issue is that this happens in LFS process also. Please check why BlockRetriever is active even when LFS process is not done.

@tgrospic BlockRetriever is called as part of Casper loop 
https://github.com/rchain/rchain/blob/bef0a1462e986c85606e1a1c55b544c1ff037b00/node/src/main/scala/coop/rchain/node/runtime/Setup.scala#L275-L285
which is started immediately on node startup. Im not sure there is an easy way to fix this.

File: casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala (hunk 5 above)
Comment (nzpr) [reply casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala]: Yes you are right, I removed this test case https://github.com/rchain/rchain/pull/3634/commits/f86b0efe45c42fdf2351f532eacb44950eeef0b4

**Comment by tgrospic** [comment]
> which is started immediately on node startup. Im not sure there is an easy way to fix this.

@nzpr OK, we can address this with as part of BlockReceiver #3650 changes.

**Review by tgrospic — APPROVED** [review]
LGTM

**Review by stanislavlyalin — APPROVED** [review]
LGTM.

**Comment by nzpr** [comment]
bors merge
