### PR TITLE
[RPC] Sync feature/v0.12-rpc with feature/v0.12 (included block hash fix)

### LINKED ISSUE #3708: Update RPC branch with the block hash fix
## Overview

RPC release is based on v0.12.x release line. It's patched with the fix for block hash and block version 2.

## Solution

- [x] Merge `feature/v0.12` branch to `feature/v0.12-rpc`.
- [x] Create a new RPC release with the version `v0.12.8+rpc`.

### PR DESCRIPTION
**Pull request by stanislavlyalin**
## Overview

This pull request migrates the latest changes from the `feature/v0.12` branch to the `feature/v0.12-rpc` branch, including the block hash fix.

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Review by tgrospic — APPROVED** [review]
LGTM

**Comment by stanislavlyalin** [comment]
bors merge

**Review by nzpr — APPROVED** [review]
LGTM

**Comment by stanislavlyalin** [comment]
bors merge

File: casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala [hunk 1]
```diff
@@ -498,21 +498,22 @@ class MultiParentCasperAddBlockSpec extends FlatSpec with Matchers with Inspecto
...
-        status1      <- nodes(1).processBlock(invalidBlock)
-        status2      <- nodes(2).processBlock(invalidBlock)
-        signedBlock2 <- nodes(1).createBlockUnsafe()
-        status3      <- nodes(1).processBlock(signedBlock2)
-        bonds        <- nodes(1).runtimeManager.computeBonds(ProtoUtil.postStateHash(signedBlock2))
-        _            = bonds.map(_.stake).min should be(0) // Slashed validator has 0 stake
-        _            <- nodes(2).handleReceive()
-        signedBlock3 <- nodes(2).createBlockUnsafe()
-        status4      <- nodes(2).processBlock(signedBlock3)
+        deployData    <- ConstructDeploy.basicDeployData[Effect](0, shardId = SHARD_ID)
```
Comment (tgrospic) [inline casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala:501]: It seems that shard was left out here so your fix in added commit looks legitimate.

Comment (stanislavlyalin) [reply casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala:501]: I meant that there are some places in this file where `basicDeployData` is called, but `SHARD_ID` is not filled. To avoid possible problems, maybe it's worth adding the `SHARD_ID` filling there and doing it also for the `v0.12` branch?

**Comment by stanislavlyalin** [comment]
bors merge

File: casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala (hunk 1 above)
Comment (stanislavlyalin) [reply casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala:501]: I initiated merging of PR as the change is needed urgently. Fix can be done after.

Comment (tgrospic) [reply casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala:501]: No need to fix it. `feature/v0.12` is not updated with shard ID in deploy data, only RPC branch.
