### PR TITLE
Fix sync and migration on compacted state 

### LINKED ISSUE #3471: Startup and migration error with v0.11.0-rc1
## Overview

Testing `v0.11.0-rc1` version revealed errors in startup on test net in the process of getting the Last Finalized State and on main net when node started migration of LFB to DAG storage.

Test net logs:
[test-net-fresh-start-error.log](https://github.com/rchain/rchain/files/6794888/test-net-fresh-start-error.log)

Main net logs:
[main-net-migration-error.log](https://github.com/rchain/rchain/files/6794889/main-net-migration-error.log)

### PR DESCRIPTION
**Pull request by nzpr**
## Overview
Closes https://github.com/rchain/rchain/issues/3471

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

File: block-storage/src/main/scala/coop/rchain/blockstorage/finality/LastFinalizedKeyValueStorage.scala [hunk 1]
```diff
@@ -59,11 +59,15 @@ class LastFinalizedKeyValueStorage[F[_]: Sync] private (
...
-        .bfTraverse(List(lfb)) { bh =>
-          blocksInfoMap.get(bh).map(_.parents.toList).getOrElse(List.empty)
-        }
-        .toList
+      finalizedBlockSet <- DagOps
+                            .bfTraverseF(List(lfb)) { bh =>
+                              blocksInfoMap
+                                .get(bh)
+                                // with trimmed state edge parents might not be in the blockmetadataDB, so filter them out
+                                .map(_.parents.toList.filterA(blockMetadataDb.contains(_)))
```
Comment (nzpr) [inline block-storage/src/main/scala/coop/rchain/blockstorage/finality/LastFinalizedKeyValueStorage.scala:67]: On compacted state finalized block set during migration were including edge blocks parents, which do not exist in metadata store. Fix is filtering them out.

File: casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala [hunk 2]
```diff
@@ -246,9 +246,9 @@ class Initializing[F[_]
         .map(_.latestBlockHash)
         .toSet
 
-      // Add sorted DAG in order from oldest to approved block
+      // Add sorted DAG in order from approved block to oldest
       minHeight <- getMinBlockHeight
-      _ <- heightMap.flatMap(_._2).toList.traverse_ { hash =>
+      _ <- heightMap.flatMap(_._2).toList.reverse.traverse_ { hash =>
```
Comment (nzpr) [inline casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala:251]: We have to add LFB first, because each `DagStore.insert` returns DagRepresentation, which requires having finalized block in DagStore. Also each insert checks consistency of the DAG (heights should be continuous)
https://github.com/rchain/rchain/blob/56c35c0ecbdc2b5ba0d5cd5a02c960fb7d7d4e74/block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockMetadataStore.scala#L186-L192
So fix is to add blocks in reverse order - down from LFB.

**Review by tgrospic — APPROVED** [review]
LGTM

**Review by zsluedem — APPROVED** [review]
LGTM

**Comment by nzpr** [comment]
bors merge
