### PR TITLE
Make Justification regression work with LFS

### LINKED ISSUE #3119: Justification Regression validation might be broken with LFS
Current logic of justification regression check has flaw:

Hope graph and `dot` notation or graph below helps understanding the issue.
```dot
digraph G {
  bX ->  LFS
  LFS -> LMv1
  LFS -> bA
  LFS -> LMv3
  LFS -> LMv4
  LFS -> LMv5


  LMv1 -> B1
  B1 -> bA
}
```
Screenshot 2020-09-08 at 16 18 28
Let assume validator A (`vA`) has been bonded in block `bA`, but does not produce any blocks.

When new block `bX` having `bA` as justification is being added, it is being checked for justification regression.
This involves comparing two justifications originated by `vA`: for block `bX` (name it `jXA`) and block `bA` (name it `jAA`).

As `vA` just been bonded in `bA`, this means that `jAA`is non existent.

In this case genesis block used for justification. 
https://github.com/rchain/rchain/blob/dac6dab1e7e21bbdd1b910a41adcdd591ba90349/casper/src/main/scala/coop/rchain/casper/Validate.scala#L593-L597
Which is wrong, because with introducing of approved (finalised) state genesis block can have greater height then `bA`

Suggested change - assume no justification regression in this case without involving genesis.

### PR DESCRIPTION
**Pull request by nzpr**
Testing of LFS revealed (unexpectedly) possible flaw in justification regression detector.

JR detector can be broken when validator bonds and does not propose blocks.

More info in related issue

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by nzpr** [comment]
I made some refactoring as well, but the fix is basically is this part of the code
https://github.com/rchain/rchain/blob/dac6dab1e7e21bbdd1b910a41adcdd591ba90349/casper/src/main/scala/coop/rchain/casper/Validate.scala#L593-L597 to assume no regression if `!previousLatestMessages.contains(previousLatestMessages)`

**Comment by tgrospic** [comment]
Should we add this to dev and rebase LFS?

**Comment by nzpr** [comment]
@tgrospic I believe its ok if we have it in LFS only, its not some urgent bugfix

File: casper/src/main/scala/coop/rchain/casper/Validate.scala [hunk 1]
```diff
@@ -545,105 +545,73 @@ object Validate {
...
+                  .buildString(sender)} has a lower sequence number than ${PrettyPrinter
+                  .buildString(currentHash)}."
+                Log[F].warn(ignore(b, msg))
+              }
+              // Compare and check for regression
+              val regressionDetected = for {
+                curJustificationHash <- curLMs(sender).pure[F]
+                newJustification     <- dag.lookupUnsafe(newJustificationHash)
+                curJustification     <- dag.lookupUnsafe(curJustificationHash)
+                regression           = (!newJustification.invalid && newJustification.seqNum < curJustification.seqNum)
```
Comment (tgrospic) [inline casper/src/main/scala/coop/rchain/casper/Validate.scala]: 3 LOC instead of 26. Nice :smile:

File: casper/src/main/scala/coop/rchain/casper/Validate.scala [hunk 2]
```diff
@@ -545,105 +545,73 @@ object Validate {
...
+            } else {
+              def logWarn(currentHash: BlockHash, regressiveHash: BlockHash): F[Unit] = {
+                val msg = s"block ${PrettyPrinter.buildString(regressiveHash)} by ${PrettyPrinter
+                  .buildString(sender)} has a lower sequence number than ${PrettyPrinter
+                  .buildString(currentHash)}."
+                Log[F].warn(ignore(b, msg))
+              }
+              // Compare and check for regression
+              val regressionDetected = for {
+                curJustificationHash <- curLMs(sender).pure[F]
```
Comment (tgrospic) [inline casper/src/main/scala/coop/rchain/casper/Validate.scala]: There is no need to wrap this in `F` just to be used in `for` comprehension. It can be defined as "normal" variable before `for`.

**Review by tgrospic — APPROVED** [review]
Very nice fix!

**Comment by tgrospic** [comment]
In equivocation check is another place where genesis is also used. We should see how this is reflected with LFS.
https://github.com/rchain/rchain/blob/006e728637bc363a273fda70f7b663c0d10cb956/casper/src/main/scala/coop/rchain/casper/EquivocationDetector.scala#L274-L285

File: casper/src/main/scala/coop/rchain/casper/Validate.scala (hunk 2 above)
Comment (nzpr) [reply casper/src/main/scala/coop/rchain/casper/Validate.scala:600]: Yeah, I do this to avoid additional bracket section, makes it less readable

**Review by zsluedem — APPROVED** [review]
Good work!

**Comment by nzpr** [comment]
bors merge

**Comment by nzpr** [comment]
bors merge
