### PR TITLE
Use one gRPC channel per peer

### LINKED ISSUE #3005: Error with gRPC streaming: cancelled before receiving half close
gRPC server when node is under load might refuse to process streamed messages (blocks)
https://github.com/rchain/rchain/blob/2e870e1fb196fff4775b249b201af29346fdca54/comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportReceiver.scala#L77

with error
```
Could not receive stream! CANCELLED: cancelled before receiving half close
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
```
As per https://grpc.github.io/grpc/core/md_doc_core_transport_explainer.html
this means that server cancelled gRPC channel before client said that it has no more data to push.
It's not clear yet whether the problem is on server or on client side

Piece of code related as well

https://github.com/rchain/rchain/blob/7de591c89dc120abdbee7b93bfa791d003b4818b/comm/src/main/scala/coop/rchain/comm/transport/SslSessionServerInterceptor.scala#L34-L39

### PR DESCRIPTION
**Pull request by nzpr**
Attempt to address this issue https://github.com/rchain/rchain/issues/3005
ATM each p2p call opens new gRPC connection, which does TLS handshake, allocates TCP port and so on. 
This PR makes transport client open a single gRPC connection per peer and use it for all subsequent calls.

Also as per https://github.com/grpc/grpc/issues/7058 `channels are intended to be shared among stubs.`

For now it's not clear if we can/should go even further and use a single stub to execute all requests, that needs some research.
https://github.com/rchain/rchain/blob/ff17c3988c43ce7d038c30e20fb7da511634dd39/comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportClient.scala#L128-L131

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

**Comment by nzpr** [comment]
@zsluedem @tgrospic I was able to successfully sync from scratch 250k blocks, no errors from this issue https://github.com/rchain/rchain/issues/3005

File: comm/src/main/scala/coop/rchain/comm/transport/TransportLayer.scala [hunk 1]
```diff
@@ -15,6 +15,7 @@ trait TransportLayer[F[_]] {
   def broadcast(peers: Seq[PeerNode], msg: Protocol): F[Seq[CommErr[Unit]]]
   def stream(peer: PeerNode, blob: Blob): F[Unit]
   def stream(peers: Seq[PeerNode], blob: Blob): F[Unit]
+  def shutdown(): F[Unit]
```
Comment (tgrospic) [inline comm/src/main/scala/coop/rchain/comm/transport/TransportLayer.scala]: This operation is not necessary on Transport interface it's more implementation detail. In NodeRuntime we have instance of concrete implementation which can be used directly.

But I don't think Netty channels needs special treatment to close it when process is closing. Is there a reason to do this, like preventing a thread to exit?

Comment (nzpr) [reply comm/src/main/scala/coop/rchain/comm/transport/TransportLayer.scala]: @tgrospic I'm more thinking about releasing channels for peers. Transport is a set of channels for client calls, they are up and available while node is running. I'm not sure whats the procedure for releasing resources on the counterparty when node is just Ctrl+C-ed, so I put this to explicitly close all client connections. Do you think this is unnecessary?

**Review by zsluedem — APPROVED** [review]
LGTM

File: comm/src/main/scala/coop/rchain/comm/transport/TransportLayer.scala (hunk 1 above)
Comment (nzpr) [reply comm/src/main/scala/coop/rchain/comm/transport/TransportLayer.scala]: I see, Netty should close channels itself on shutdown, so this part of the code is not necessary. I'll remove commit https://github.com/rchain/rchain/pull/3006/commits/c12e23411b8899c374af6a77a8b0ea321b44af99

**Review by tgrospic — APPROVED** [review]
Nice work!

**Comment by nzpr** [comment]
bors merge
