### PR TITLE
[RPC] Add short circuit boolean evaluation

### LINKED ISSUE #3362: Boolean operators and/or are evaluated eagerly (add lazy &&/||)
### What did you expect to see?
Boolean operators should lazy evaluate operands.

**UPDATE: Instead if changing behavior of existing `and` and `or` boolean operators, lazy variants will be added `&&` and `||`.**

### What did you see instead?
The error _Error: Method `get` is not defined on String._ is reported instead.

### Steps to reproduce the bug
`if(false and ("x".get(0))) {}` should not throw error because the first operand `false` makes the whole expression false.

https://github.com/rchain/rchain/blob/09d9acc916e008dc93a7289202262fd5a4d9d41d/rholang/src/main/scala/coop/rchain/rholang/interpreter/Reduce.scala#L605-L617

Related issue: #3344

### PR DESCRIPTION
**Pull request by zsluedem**
## Overview

Same commits like https://github.com/rchain/rchain/pull/3649 but for rpc branch

Add `&&` and `||` syntax for rholang which support short circuit boolean evaluation. 

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

### CODE REVIEW

File: rholang/src/test/scala/coop/rchain/rholang/interpreter/ShortCircuitBooleanSpec.scala [hunk 1]
```diff
@@ -0,0 +1,206 @@
...
+                    #    ret1!(false) |
+                    #    for(@x1 <- ret1) {
+                    #        ret2!(x1)|
+                    #        for (@x2 <- ret2){
+                    #          // same like above
+                    #          @"${outcomeCh}"!(x2 and not x1 || true)
+                    #        }
+                    #    }
+                    #
+                    #}""".stripMargin('#')
```
Comment (hilltracer) [inline rholang/src/test/scala/coop/rchain/rholang/interpreter/ShortCircuitBooleanSpec.scala]: I think It looks more readable:
```scala
  "&& and ||" should {
    "substitute right for bound var in embedded scope" in {
      // If substituting don't work in && (or ||) - x1 would be unbound
      val term = s""" new ret1, ret2 in {
                    #    ret1!(false) |
                    #    for(@x1 <- ret1) {
                    #        ret2!(Nil)|
                    #        for (_ <- ret2) {
                    #            @"${outcomeCh}"!(true && x1) 
                    #        }  
                    #    }
                    #}""".stripMargin('#')

      execute(term).runSyncUnsafe(maxDuration) should equal(Right(false))

      val term2 = s""" new ret1, ret2 in {
                    #    ret1!(true) |
                    #    for(@x1 <- ret1) {
                    #        ret2!(Nil)|
                    #        for (_ <- ret2){
                    #          @"${outcomeCh}"!(false || x1)
                    #        }
                    #    }
                    #
                    #}""".stripMargin('#')

      execute(term2).runSyncUnsafe(maxDuration) should equal(Right(true))
    }
```

File: rholang/src/test/scala/coop/rchain/rholang/interpreter/ShortCircuitBooleanSpec.scala [hunk 2]
```diff
@@ -0,0 +1,206 @@
...
+    "substitute right for bound var in embedded scope" in {
+      val term = s""" new ret1, ret2, stdout(`rho:io:stdout`) in {
+                    #    ret1!(false) |
+                    #    for(@x1 <- ret1) {
+                    #        ret2!(x1)|
+                    #        for (@x2 <- ret2){
+                    #          // raise error here if substitute(commit 02f2410848b53afbb266d94c0beef06734be4fc4)
+                    #          // is not enabled
+                    #          // x1 would be unbound
+                    #          // https://discord.com/channels/391435113415573504/958777729791180800/959369185127968779
```
Comment (hilltracer) [inline rholang/src/test/scala/coop/rchain/rholang/interpreter/ShortCircuitBooleanSpec.scala]: This link is not opening.

**Review by hilltracer — APPROVED** [review]
I looked at the code and played around with the implementation in VS studio. I don't see what else can be fixed here. But we need to test how the implementation works in practice (with Multisig contract).
