### PR TITLE
Fix generation of bonds and wallets file

### LINKED ISSUE #3008: Node does not create random bonds file
This piece of code should be adjusted, as `maybeBondsPath` is always set
 
https://github.com/rchain/rchain/blob/e2bbe2f5a28996916d23565b2d3a3bbaac9e7187/casper/src/main/scala/coop/rchain/casper/util/BondsParser.scala#L57-L70

### PR DESCRIPTION
**Pull request by nzpr**
Some old PR refactoring config https://github.com/rchain/rchain/commit/e2bbe2f5a28996916d23565b2d3a3bbaac9e7187 broken autogeneration of bonds file and made node require wallets file without any fallback.

This PR fixes user experience.

**The rule for bonds:** if no bonds file at path specified (or default `genesis_path/bonds.txt` if nothing specified) does not exist - node will generate one for user. If bonds file exists but is empty node will report error and exit.
**The rule for wallets:** if no wallets file - node reports that genesis won't have any genesis vault. No exception possibly thrown. Empty wallets file is allowed.

closes https://github.com/rchain/rchain/issues/3008

### CODE REVIEW

**Comment by tgrospic** [comment]
@nzpr Please add to the description of PR a short summary of what changes are done in the code. This should be the complement to linked issue. If there is no linked issue, PR should also contain the info about the problem it solves.

File: casper/src/main/scala/coop/rchain/casper/util/BondsParser.scala [hunk 1]
```diff
@@ -40,52 +50,45 @@ object BondsParser {
...
-        )
-    }
+      bondsPathStr: String,
+      autogenShardShize: Int
+  ): F[Map[PublicKey, Long]] = {
+    val bondsPath = Paths.get(bondsPathStr)
+    exists(bondsPath).ifM(
+      Log[F].info(s"Parsing bonds file ${bondsPath}.") >> parse(bondsPath),
+      Log[F].warn(s"BONDS FILE NOT FOUND: ${bondsPath}. Creating file with random bonds.") >>
+        newValidators[F](autogenShardShize, Path.of(bondsPathStr).toAbsolutePath)
```
Comment (tgrospic) [inline casper/src/main/scala/coop/rchain/casper/util/BondsParser.scala]: Typo Shize -> Size.

File: casper/src/main/scala/coop/rchain/casper/util/VaultParser.scala [hunk 2]
```diff
@@ -51,17 +34,19 @@ object VaultParser {
...
-    Sync[F].fromEither(
-      fromLine(line)
-        .leftMap(errMsg => new RuntimeException(s"Error in parsing vaults file: $errMsg"))
-    )
+    Sync[F]
+      .fromEither(
+        fromLine(line)
+          .leftMap(errMsg => new RuntimeException(s"FAILED PARSING WALLETS FILE: $errMsg"))
+      )
+      .flatMap(r => Log[F].info(s"Wallet loaded: ${line}").as(r))
```
Comment (tgrospic) [inline casper/src/main/scala/coop/rchain/casper/util/VaultParser.scala]: This can be simplified to only use applicative.
```scala
... <* Log[F].info(s"Wallet loaded: ${line}")
```

File: casper/src/main/scala/coop/rchain/casper/util/VaultParser.scala [hunk 3]
```diff
@@ -1,47 +1,30 @@
...
+      vaultsPathStr: String
+  ): F[Seq[Vault]] = {
+    val vaultsPath = Paths.get(vaultsPathStr)
+    exists(vaultsPath).ifM(
+      Log[F]
+        .info(s"Parsing wallets file ${vaultsPath}.") >>
+        parse[F](vaultsPath),
+      Log[F]
+        .warn(s"WALLETS FILE NOT FOUND: ${vaultsPath}. No vaults will be put in genesis block.")
+        .map(_ => Seq.empty[Vault])
```
Comment (tgrospic) [inline casper/src/main/scala/coop/rchain/casper/util/VaultParser.scala]: This can be just `as(Seq.empty[Vault])`.

**Review by tgrospic — APPROVED** [review]
LGTM, just a few minor comments.

**Review by zsluedem — APPROVED** [review]
LGTM

**Comment by nzpr** [comment]
bors merge

**Comment by nzpr** [comment]
bors merge

**Comment by nzpr** [comment]
bors merge
